- Cargo.lock
- rpc/server/src/module/account_rpc.rs
- rpc/server/src/module/mod.rs
- wallet/api/Cargo.toml
- wallet/api/src/error.rs
- wallet/api/src/lib.rs
- wallet/api/src/mock/keypair_wallet.rs
- wallet/api/src/mock/mock_wallet_service.rs
- wallet/api/src/service.rs
- wallet/api/src/store.rs
- wallet/api/src/types.rs
- wallet/api/src/wallet.rs
- wallet/lib/src/keystore_wallet.rs
- wallet/service/src/actor.rs
- wallet/service/src/message.rs
- wallet/service/src/service.rs
desgin and specific error for wallet account service.
Basically, They're WalletError, AccountServiceError.
WalletError is the most detailed one.
ServiceError make use these error kinds to display module level error.
For users, there is a RpcError to display api level error.
> [error]: add error kind for account service

- config/src/metrics_config.rs
Default use localhost, and random port when in dev mode.
> [config]: fix metric config

- cmd/starcoin/src/dev/deploy_cmd.rs
- cmd/starcoin/src/dev/execute_cmd.rs
- docs/deploy_move_contract.md
- rpc/api/src/types/pubsub.rs
- rpc/client/src/chain_watcher.rs
- rpc/client/src/lib.rs
- rpc/client/src/pubsub_client.rs
- rpc/server/src/module/pubsub/event_subscription_actor.rs
implement a chain watcher.
Client and watch block by block number, and watch txn by txn hash.
In both case, corresponding block info will be returned to client.
> [rpc]: add chain watcher in client module

- benchmarks/src/chain.rs
- benchmarks/src/sync.rs
- chain/src/tests/test_block_chain.rs
- miner/src/lib.rs
- miner/tests/miner_test.rs
- node/src/node.rs
- sync/tests/full_sync_test.rs
- sync/tests/state_sync_test.rs
- sync/tests/txn_sync_test.rs
- txpool/api/src/lib.rs
- txpool/src/lib.rs
- txpool/src/test_helper.rs
- txpool/src/tx_pool_service_impl.rs
This PR refactor txpool into async part and sync part.
Upper layer should use the sync api, and the async actor is for internal use.
For now, only miner actor is refactored to use sync api, to verify the api usability.
To make this PR smaller, I will issue another PRs to refactor other modules which rely on the async api.
Once all modules switch to sync api, the async api can be removed.
> [refactor]: add sync service api for txpool

- executor/benchmark/src/lib.rs
- executor/src/executor_test.rs
- vm/vm-runtime/src/starcoin_vm.rs
add execute transaction output write to block cache, fix execute same account multi transaction error.
> [executor] add execute transaction output write to block cache

- commons/scmd/examples/hello_main.rs
- commons/scmd/src/context.rs
- commons/scmd/src/result.rs
1. 支持 exec_with_args，可以直接传递 args 去执行某个命令，并可以直接获取到命令执行的结果。
2. 优化 CmdContext 的初始化方式，方便集成测试。
resolve #617
> [scmd] enhancement

- .github/workflows/build_test.yml
- chain/src/chain.rs
- chain/src/chain_service.rs
- chain/src/lib.rs
- chain/src/message/mod.rs
- chain/src/mock/mock_chain_service.rs
- cmd/starcoin/src/chain/get_block_cmd.rs
- cmd/starcoin/src/chain/get_txn_by_block_cmd.rs
- cmd/starcoin/src/chain/get_txn_cmd.rs
- cmd/starcoin/src/chain/get_txn_info_cmd.rs
- cmd/starcoin/src/chain/mod.rs
- cmd/starcoin/src/main.rs
- core/traits/src/chain.rs
- core/traits/src/chain_service.rs
- rpc/api/src/chain/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/chain_rpc.rs
- rpc/server/src/module/pubsub/event_subscription_actor.rs
- storage/src/block/mod.rs
- storage/src/lib.rs
- storage/src/transaction_info/mod.rs
- vm/types/src/transaction/mod.rs
This PR fix txn_info storage.
and refactor(cleanup) some apis in store, chain reader and chain service.
Besides, a new cli cmd called get_txn_info_by_block_and_index is added, which can get txn info of txn at `index` of a `block`.
The API of `get_txn_info_by_version` is implemented, but no cli cmd is exposed for now.
Once the version information of txn is exposed to user, this cli cmd can be implemented then.
I will fire another PR to address this.
> [storage&rpc]: fix txn info store

- cmd/starcoin/src/dev/compile_cmd.rs
- cmd/starcoin/src/dev/execute_cmd.rs
- vm/compiler/src/lib.rs
Make Execute support exec bytecode or move source, move source can be script or module.
If it's module, a module txn will be submitted.
> cli: support execute move source file and move bytecode file

- Cargo.lock
- cmd/starcoin/src/lib.rs
- cmd/starcoin/src/main.rs
- testsuite/Cargo.toml
- testsuite/features/cmd.feature
- testsuite/tests/integration.rs
- testsuite/tests/steps/cmd.rs
通过 cargo test --test integration -e cmd 命令单独执行，目前加了三个回环用例：
参考 Scenario Outline: [cmd]  cli continuous 1-3
以后添加需要注意修改 jsonpath的解析参数，例如：$.account.address
> [integration-test] integration test add enhance of multiple commands

- vm/vm-runtime/src/starcoin_vm.rs
StatusCode::ABORTED is converted to StatusType::Execution.
This is not expected. Use StatusCode::UNKNOWN_STATUS instead.
> [vm] fix bug in error code conversion

- network-rpc/src/tests.rs
- network/api/src/lib.rs
- network/src/network.rs
- sync/src/block_connector/mod.rs
- sync/src/block_sync/mod.rs
- sync/src/download.rs
- test-helper/src/dummy_network_service.rs
The external interface of Network uniformly uses the PeerId which implements serialization.
> network: Unify peer_id

- Cargo.lock
- Cargo.toml
- dataformat-generator/Cargo.toml
- dataformat-generator/build.rs
- dataformat-generator/src/lib.rs
- etc/starcoin_types.yml
- vm/types/src/transaction/mod.rs
Use serde-reflection to generate starcoin_types.yml.
meant to replace the handwriting located in testsuite.
> a build crate to gen starcoin_types

- chain/src/tests/block_test_utils.rs
- network-p2p/src/service_test.rs
- network-rpc/api/src/lib.rs
- network-rpc/src/rpc.rs
- network/api/src/lib.rs
- network/api/src/peer_provider.rs
- sync/Cargo.toml
- sync/src/block_connector/block_connect_test.rs
- sync/src/block_connector/mod.rs
- sync/src/block_connector/write_block_chain.rs
- sync/src/block_sync/mod.rs
- sync/src/block_sync/test_block_sync.rs
- sync/src/download.rs
- sync/src/helper.rs
- sync/src/lib.rs
- sync/src/state_sync/mod.rs
- sync/src/state_sync/test_state_sync.rs
- sync/src/sync.rs
- sync/src/txn_sync/mod.rs
- sync/src/verified_rpc_client.rs
- sync/tests/full_sync_test.rs
- sync/tests/txn_sync_test.rs
- test-helper/src/dummy_network_service.rs
- types/src/block.rs
[network & sync] Add a VerifiedRpcClient to handle rpc request verify and peer auto select.
[network-rpc] Unify network rpc method name and add a get_blocks method to VerifiedRpcClient
> Unify network rpc method name and Add a VerifiedRpcClient

- vm/stdlib/modules/PackageTxnManager.move
- vm/stdlib/modules/doc/PackageTxnManager.md
[stdlib] Fix typo:
sepc_get_upgrade_plan -> spec_get_upgrade_plan
sepc_get_module_upgrade_strategy -> spec_get_module_upgrade_strategy
> [stdlib] Fix typo in PackageTxnManager.move and the corresponding PackageTxnManager.md

- cmd/starcoin/src/node/sync/start_cmd.rs
- network/src/net.rs
- rpc/api/src/sync_manager.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/sync_manager_rpc.rs
- sync/api/src/lib.rs
- sync/api/src/service.rs
- sync/src/block_connector/block_connector_service.rs
- sync/src/sync2.rs
1. [sync] sync start cmd supports sync from specified peers.
2. [network] Temporarily disable allow_private_ipv4 in TransportConfig.
>  [sync] sync start cmd supports sync from specified peers.

- cmd/faucet/src/faucet.rs
- cmd/faucet/src/web.rs
- cmd/starcoin/src/account/accept_token_cmd.rs
- cmd/starcoin/src/account/execute_builtin_script_cmd.rs
- cmd/starcoin/src/account/transfer_cmd.rs
- cmd/starcoin/src/dev/deploy_cmd.rs
- cmd/starcoin/src/dev/execute_cmd.rs
- cmd/starcoin/src/dev/get_coin_cmd.rs
- cmd/starcoin/src/dev/sign_txn_helper.rs
- cmd/starcoin/src/dev/submit_multisig_txn_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_exe_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_plan_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_proposal_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_queue_cmd.rs
- cmd/tx-factory/src/main.rs
- commons/scs/src/lib.rs
- rpc/api/src/txpool/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/mod.rs
- rpc/server/src/module/txpool_rpc.rs
- testsuite/tests/steps/transaction.rs
- txpool/src/pool_client.rs
- vm/types/src/transaction/error.rs
定义了 txpool 和 account 的error code 转换逻辑。
这里给出 error 转换的思路：
- 内部Service 接口中的各种 CustomError，可以直接转换到 JsonRpcError。只需要实现 From trait 即可。转换时对应的是 invalid param 还是 internal error，或者需要自定义的 server error code，都可以无歧义的实现。
- 内部 Service 接口如果返回的是 anyhow::Error，这个时候需要 downcast 到具体的 CustomError，然后再走上面的逻辑，转换到 JsonRpcError。
- 无法 downcast 的，或者要 downcast 的custom error 过于通用，不知道如何映射到 jsonrpc error 的，走 internal error 的 逻辑，返回的message 中包含具体的 error 信息。
> review txpool&account rpc error code

- node/src/peer_message_handler.rs
- sync/src/block_connector/metrics.rs
- sync/src/block_connector/write_block_chain.rs
- sync/src/tasks/block_sync_task.rs
- sync/src/tasks/mod.rs
Fix node panic for block_latency metric. resolve #1771
>  [sync] Add a limit to rollback block count, for avoid use too much memory

- cmd/starcoin/src/node/sync/start_cmd.rs
- config/src/lib.rs
- config/src/network_config.rs
- config/src/sync_config.rs
- network-p2p/src/config.rs
- network-p2p/src/service.rs
- network-p2p/src/service_test.rs
- network-rpc/src/tests.rs
- network/src/service.rs
- network/src/worker.rs
- network/tests/network_node_test.rs
- network/tests/network_rpc_test.rs
- node/src/node.rs
- rpc/api/src/sync_manager.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/node_rpc.rs
- rpc/server/src/module/sync_manager_rpc.rs
- sync/api/src/lib.rs
- sync/api/src/service.rs
- sync/src/download.rs
- sync/src/sync2.rs
- sync/src/tasks/block_sync_task.rs
- sync/src/tasks/mod.rs
- sync/tests/full_sync_test.rs
- sync/tests/test_sync/mod.rs
- sync/tests/txn_sync_test.rs
- test-helper/src/network.rs
1.  将 skip-pow-verify 作为 node sync start 的参数，而不是全局参数。
2. 增加了 enable_mdns 参数，开启网络的 mdsn。
3. allow_private_ipv4 默认设置位 true。
4. 清理了一些配置项，self_address/self_peer_id 在 network config 内部 expect，而不是抛出 Error。
> [sync & network] Config refactor and cleanup

- config/src/rpc_config.rs
- node/src/lib.rs
- rpc/server/src/service.rs
In windows, named pipe for process communication must under
a special path "\\.\pipe\" that is, a pipe named "foo" would
have a full path name of "\\.\pipe\foo"
> Fix windows ipc connect

- Cargo.lock
- cmd/generator/src/main.rs
- cmd/starcoin/src/main.rs
- commons/scmd/Cargo.toml
- commons/scmd/examples/hello_main.rs
- commons/scmd/src/context.rs
- config/src/lib.rs
- testsuite/tests/steps/cmd.rs
1. Version 作为参数传递，scmd 不在自动生成 version。
2. 增加参数，让 git_version 可以正确获取到最新的 git tag。
> [cmd & scmd] Pass version/long version by args and fix git version.

- account/lib/src/account_test.rs
- block-relayer/src/block_relayer.rs
- chain/chain-notify/src/lib.rs
- chain/src/tests/test_block_chain.rs
- cmd/starcoin/src/account/accept_token_cmd.rs
- cmd/starcoin/src/account/execute_builtin_script_cmd.rs
- cmd/starcoin/src/account/transfer_cmd.rs
- cmd/starcoin/src/debug/gen_block_cmd.rs
- cmd/starcoin/src/dev/deploy_cmd.rs
- cmd/starcoin/src/dev/execute_cmd.rs
- cmd/starcoin/src/dev/get_coin_cmd.rs
- cmd/starcoin/src/dev/sign_txn_helper.rs
- cmd/starcoin/src/dev/submit_multisig_txn_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_exe_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_plan_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_queue_cmd.rs
- cmd/starcoin/src/view.rs
- cmd/tx-factory/src/main.rs
- commons/crypto/tests/crypto_hash_test.rs
- rpc/server/src/module/pubsub/tests.rs
- storage/src/transaction_info/mod.rs
- sync/tests/txn_sync_test.rs
- txpool/src/pool.rs
- txpool/src/test.rs
- vm/types/src/block_metadata.rs
- vm/types/src/transaction/mod.rs
1. Cache SignedUserTransaction id and BlockMetadata id.
2. Use txn.id() to replace txn.crypto_hash()
> [types]Reuse Transaction's id

- vm/functional-tests/tests/testsuite/check/gas_check.move
this pr add two tests:
1. txn gas must below max gas bound (40_000_000)
2. txn gas must above min gas unit (600)
when check scaling factor correctness, I found this two tests missing.
https://github.com/starcoinorg/starcoin/issues/2213
> [test] txn gas must below max gas bound and above min gas unit

- Cargo.lock
- cmd/indexer/Cargo.toml
- cmd/indexer/mappings/block.mapping.json
es 升级后，依赖tokio 1.x，但jsonrpc 依赖 tokio 0.x ，不兼容。
先回退 es 版本。
> downgrade es version to use same tokio as jsonrpc

- block-relayer/src/block_relayer.rs
- config/example/barnard/config.toml
- config/example/halley/config.toml
- config/example/proxima/config.toml
- config/src/network_config.rs
- config/src/tests.rs
- kube/manifest/starcoin-barnard.yaml
- network/src/service.rs
- network/src/worker.rs
- txpool/src/lib.rs
1. 优化了一下 CompatBlock 消息的处理机制，同步状态下依然继续处理 CompatBlock 消息。
2. 增加了配置项目，节点可以定义 p2p 网络支持的连接数。
> Optimize network message handle

- sync/src/sync.rs
- sync/tests/full_sync_test.rs
Fix #2344 and enable two ignore tests.
> [sync] Fix sync stage handle bug #2344

- network-p2p/src/request_responses.rs
先用空格切分记录了一下 network rpc 的日志，增加了 rpc 消耗的时间。
等确定 #2359 的方案了再修改。
> [network-rpc] structure network rpc request log.

- chain/chain-notify/src/lib.rs
- rpc/server/src/module/pubsub/tests.rs
> [json-rpc] Broadcast new block event to rpc subscriber when sync.

- block-relayer/src/block_relayer.rs
- network-p2p/src/behaviour.rs
- network-p2p/src/protocol.rs
- network-p2p/src/protocol/event.rs
- network-p2p/src/service.rs
- network-p2p/src/service_test.rs
- network/api/src/peer_provider.rs
- network/api/src/tests.rs
- network/src/service.rs
- network/src/worker.rs
- network/tests/network_service_test.rs
- rpc/api/src/types.rs
- sync/src/sync.rs
- sync/src/tasks/mock.rs
- sync/src/tasks/mod.rs
- sync/src/tasks/tests.rs
- types/src/peer_info.rs
1.  Peer 握手时交换互相支持的 notif protocols 和 rpc protocols.
2.  同步时只从支持 rpc_protocols 的 peer 同步。当前节点在 handshake 消息中未携带 rpc protocols，所以暂时不能启用过滤器。
> [network] Exchange supported notif_protocols and rpc_protocols when peer handshake

- genesis/tests/generated_files.rs
- vm/stdlib/tests/generated_files.rs
避免在 test 中调用 cargo run，直接调用编译好的二进制。
> Fix test oom killed

- config/src/stratum_config.rs
- network-rpc/api/src/lib.rs
- network-rpc/derive/src/to_client.rs
- network-rpc/src/lib.rs
- network/api/src/peer_provider.rs
- network/src/service.rs
- network/src/service_ref.rs
- network/src/worker.rs
- network/tests/network_rpc_test.rs
- node/src/lib.rs
- node/src/network_service_factory.rs
- node/src/node.rs
- stratum/src/service.rs
- stratum/src/stratum.rs
- sync/src/sync.rs
- sync/src/tasks/mock.rs
- sync/src/tasks/mod.rs
- sync/src/txn_sync/mod.rs
- sync/tests/test_sync/mod.rs
- types/src/peer_info.rs
1. 同步时过滤不支持 rpc 接口的 peer。
2. 修复几个会导致测试用例偶发失败的 bug。
> [sync] Enable support rpc filter when sync.

- network-p2p/src/discovery.rs
- network-p2p/src/service.rs
> [network-p2p]add max_connections_per_address.

- cmd/indexer/src/es_sinker.rs
先更新 tip header，再删除es 数据。
如果 client 解析不成功，重试会拿到更新后 的tip header。
> indexer: fix #2493

- developer.starcoin.org/content/setup/run_by_docker.md
- developer.starcoin.org/content/setup/run_by_docker.zh.md
This ~ will be translated in host and lead to no-file-found error if current user was not root.
> Should not assume current user is root

- Cargo.lock
- cmd/miner_client/src/job_client.rs
- miner/Cargo.toml
- miner/src/job_bus_client.rs
- miner/src/lib.rs
- miner/tests/miner_test.rs
- node/src/node.rs
- rpc/api/src/miner.rs
- rpc/api/src/types.rs
- rpc/api/src/types/pubsub.rs
- rpc/client/src/lib.rs
- rpc/client/src/pubsub_client.rs
- rpc/client/tests/client_server_test.rs
- rpc/server/src/module/miner_rpc.rs
- rpc/server/src/module/pubsub.rs
- rpc/server/src/module/pubsub/tests.rs
- stratum/src/rpc.rs
- stratum/src/stratum.rs
- types/Cargo.toml
- types/src/block.rs
- types/src/system_events.rs
APIs change:
1. Return block hash in minting.submit
2. Add prevous_hash in subscribe MintBlockEvent
3. Add new rpc mining.get_job for getting MintBlockEvent
Optimize codes:
1. Clean struct MintBlock
2. Send seal event to MinerService instead of bus
> rpc&&miner: Update miner && related apis

- Cargo.lock
- account/Cargo.toml
- account/api/src/error.rs
- account/api/src/message.rs
- account/api/src/rich_wallet.rs
- account/api/src/service.rs
- account/api/src/types.rs
- account/service/src/service.rs
- account/src/account.rs
- account/src/account_manager.rs
- account/src/account_storage.rs
- account/src/account_test.rs
- cmd/starcoin/src/account/import_readonly_cmd.rs
- cmd/starcoin/src/account/mod.rs
- cmd/starcoin/src/lib.rs
- rpc/api/src/account/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/account_rpc.rs
- vm/types/src/receipt_identifier.rs
新增 account import-readonly 命令通过公钥导入只读账号
TODO
1. 更新默认账号时触发事件通知其他服务。
2. 增加文档
> Support readonly account

- benchmarks/src/lib.rs
- chain/tests/test_block_chain.rs
- chain/tests/test_opened_block.rs
- cmd/faucet/src/faucet.rs
- cmd/faucet/src/web.rs
- cmd/starcoin/src/account/receipt_identifier_cmd.rs
- cmd/starcoin/src/account/transfer_cmd.rs
- cmd/starcoin/src/dev/get_coin_cmd.rs
- cmd/starcoin/src/dev/tests.rs
- cmd/tx-factory/src/main.rs
- cmd/tx-factory/src/txn_generator.rs
- executor/benchmark/src/lib.rs
- executor/src/account.rs
- executor/src/error_code_test.rs
- executor/tests/executor_test.rs
- rpc/server/src/module/pubsub/tests.rs
- sync/tests/txn_sync_test.rs
- testsuite/tests/steps/transaction.rs
- txpool/src/test.rs
- vm/transaction-builder/src/lib.rs
- vm/types/src/receipt_identifier.rs
- vm/types/src/transaction/authenticator.rs
转账使用 peer_to_peer_v2  function，废弃 auth key 参数
> [transaction] Use peer_to_peer_v2 when transfer, deprecated auth key parameter.

- vm/transaction-builder-generator/src/generate.rs
- vm/transaction-builder-generator/src/lib.rs
- vm/transaction-builder-generator/tests/generation.rs
用一个临时的办法 fix #2608 
script function 支持 vector 参数后， transaction-builder-generator 尚未支持，当前的一个临时办法是生成代码的时候先跳过这种类型的脚本，当前只有两个 batch_peer_to_peer 和 batch_peer_to_peer_v2。
> [transaction-builder-generator] fix transaction builder generator for skip vector<T> arguments script.

- executor/src/account.rs
- executor/tests/module_upgrade_test.rs
- executor/tests/treasury_withdraw_test.rs
- state/api/src/chain_state.rs
- vm/transaction-builder/src/lib.rs
- vm/types/src/account_config/resources/balance.rs
- vm/types/src/on_chain_resource/dao/mod.rs
- vm/types/src/on_chain_resource/treasury.rs
- vm/types/src/token/token_code.rs
- vm/types/src/token/token_info.rs
- vm/vm-runtime/src/starcoin_vm.rs
close https://github.com/starcoinorg/starcoin/issues/2628
> fix nested token code

- .github/workflows/release_asset.yml
- docker/Dockerfile
- scripts/install_llvm.ps1
- scripts/release.sh
1. 从 artifacts 里清理掉了一些不常用的二进制，减少压缩包大小。
2. 升级 llvm 版本尝试修复 windows build 失败的问题
> [ci] Fix build on windows

- cmd/starcoin/src/dev/call_api_cmd.rs
- cmd/starcoin/src/dev/mod.rs
- cmd/starcoin/src/lib.rs
- node/src/rpc_service_factory.rs
- rpc/api/src/contract_api.rs
- rpc/api/src/types.rs
- rpc/server/src/module/account_rpc.rs
- rpc/server/src/module/contract_rpc.rs
- rpc/server/src/module/helpers.rs
- vm/types/src/transaction/mod.rs
1. 提供 dry_run RawUserTransaction rpc api。
2. 提供 dev call-api 命令，可调用任意的 json rpc api 。
resolve #2480 #2620
> Dry run api

- Cargo.lock
- account/api/Cargo.toml
- account/api/src/message.rs
- account/api/src/service.rs
- account/api/src/types.rs
- account/service/src/service.rs
- account/src/account.rs
- account/src/account_manager.rs
- cmd/airdrop/src/main.rs
- cmd/starcoin/src/account/verify_sign_cmd.rs
- cmd/starcoin/src/cli_state.rs
- executor/src/account.rs
- rpc/api/src/account/mod.rs
- rpc/api/src/types.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/account_rpc.rs
- test-helper/src/executor.rs
- testsuite/features/cmd.feature
- vm/functional-tests/src/evaluator.rs
- vm/types/src/sign_message.rs
- vm/types/src/transaction/authenticator.rs
1. 废弃 AccountSignature， 用 TransactionAuthenticator 替代。
2. 定义 SignedMessage， 包含 SigningMessage 以及签名的账号地址。
3. 通过链上数据校验账号和公钥之间的关系。
> [account] Remove AccountSignature and define SignedMessage

- chain/src/chain.rs
- chain/tests/test_block_chain.rs
- commons/accumulator/src/accumulator_test.rs
- commons/accumulator/src/lib.rs
- commons/accumulator/src/tree.rs
> [accumulator] Fix bug for get txn info from chain

- cmd/starcoin/src/dev/deploy_cmd.rs
- cmd/starcoin/src/dev/dev_helper.rs
- cmd/starcoin/src/dev/mod.rs
- cmd/starcoin/src/dev/tests.rs
- cmd/starcoin/src/dev/upgrade_module_exe_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_proposal_cmd.rs
- cmd/starcoin/src/dev/upgrade_module_queue_cmd.rs
- cmd/starcoin/src/view.rs
- vm/transaction-builder/src/lib.rs
- vm/types/src/token/token_code.rs
1. 统一 dev 和部署相关的命令参数，兼容 mv 和 package 文件
2. 给 `dev module-proposal` 和 `dev module-queue` 增加 token code 参数，支持第三方 Token 通过治理升级合约。fix #2707
> [cli] dev deploy/upgrade_module commands's file option supports mv and package file

- types/src/block.rs
> [types] Fix block compat bug for after deprecated `author_auth_key` in BlockHeader

- Cargo.lock
- abi/resolver/Cargo.toml
- abi/resolver/src/lib.rs
- vm/resource-viewer/src/resolver.rs
修复一个 resolve 链上不存在的 module 时的 bug，该 module 需要预先放入 module cache，否则 module 中的类型引用当前 module 的其他类型时，resolve 会报错。
> [abi] Fix resolve new module by code self dependency bug.

- cmd/indexer/src/lib.rs
- cmd/starcoin/src/view.rs
- rpc/api/src/types.rs
- rpc/server/src/module/chain_rpc.rs
change type tag serialize to string in jsonrpc.
this will break existing api call.
> [BREAKING CHANGE] change type tag serialize to string in jsonrpc

- chain/api/src/errors.rs
- sync/src/block_connector/block_connector_service.rs
- sync/src/tasks/block_sync_task.rs
在 apply 之前检查该 block 是否是以前验证失败的 block
> [sync] Check failed block before apply.

- chain/api/src/chain.rs
- chain/service/src/chain_service.rs
- chain/src/chain.rs
- chain/tests/test_block_chain.rs
- cmd/starcoin/src/node/reset_cmd.rs
- node/api/src/message.rs
- node/api/src/node_service.rs
- node/src/node.rs
- rpc/api/src/node_manager.rs
- sync/src/block_connector/block_connector_service.rs
- sync/src/block_connector/mod.rs
- sync/src/block_connector/test_write_block_chain.rs
- sync/src/block_connector/write_block_chain.rs
- types/src/startup_info.rs
重新实现了 node reset 命令，用于将当前节点的区块重置到某个历史高度，然后重新执行。执行命令后无需重启节点。
用于修复数据以及故障处理。
> implement node reset

- Cargo.lock
- block-relayer/Cargo.toml
- block-relayer/src/block_relayer.rs
- chain/src/verifier/mod.rs
- cmd/starcoin/src/node/manager/mod.rs
- network-p2p/src/protocol.rs
- node/api/src/message.rs
- node/api/src/node_service.rs
- node/src/node.rs
- rpc/api/src/node_manager.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/node_manager_rpc.rs
- storage/src/block/mod.rs
- storage/src/lib.rs
- types/src/cmpact_block.rs
当前 fill_compact_block 中通过 short_id 组装 Block 时，如果从对方 peer 获取交易返回空，会导致组装出错误的区块。
所以
1. 增加验证，确保组装出正确的区块。
2. 将 p2p protocol 的 min version 改为 2，current version 改为 3， 拒绝 version 为 1 的节点（部分 barnard 网络的老节点）
3. 增加 `node manager delete-failed-block` 命令用户清理掉验证失败的区块。
> [block-relayer] Verify block body when construct block by compact block.

- abi/decoder/src/lib.rs
- cmd/starcoin/src/account/mod.rs
- cmd/starcoin/src/account/nft_cmd.rs
- cmd/starcoin/src/lib.rs
- executor/src/lib.rs
- rpc/api/src/types.rs
- vm/transaction-builder/src/lib.rs
- vm/types/src/on_chain_resource/mod.rs
- vm/types/src/on_chain_resource/nft.rs
resolve #2838 
1. 新增 `account nft list|ident|transfer` 命令用于查看 NFTGallery 中的 NFT，IdentifierNFT 中的 NFT，转让 NFT。
2. NFT 虽然定义成 MoveResource，但由于有泛型参数，当前 MoveResource 的解析不能支持泛型，所以临时通过 json 解析，未来可以考虑重构 MoveResource 的实现，支持未知类型的泛型参数解析。
> [cli] Implement `account nft` commands, for suppport show and transfer nft.

- vm/move-cli/src/main.rs
use interface_dir only when running functional test.
```
move clean
move check
move publish
move functional-test
```
> move-cli: fix ft when check with local

- Cargo.lock
- rpc/client/Cargo.toml
This reverts commit d2ca455742bf5eac7295712d1c4b0b0ec5ccd93a.
> Revert "Bump parity-tokio-ipc from 0.8.0 to 0.9.0 (#2900)"

- benchmarks/Cargo.toml
- benchmarks/README.md
- benchmarks/benches/bench_chain.rs
- benchmarks/benches/bench_state_tree.rs
- benchmarks/benches/bench_storage.rs
- benchmarks/benches/bench_vm.rs
> pprof use only linux

- storage/src/block/mod.rs
- storage/src/lib.rs
> unsave block body

- Cargo.lock
- vm/natives/Cargo.toml
- vm/natives/src/ecrecover.rs
- vm/natives/src/hash.rs
- vm/natives/src/lib.rs
- vm/vm-runtime/src/natives.rs
基础 ecrecover 方法实现，但尚未暴露到 Move 中，Move 中的方法签名如下：
```
native public fun ecrecover(hash: vector<u8>, signature: vector<u8>): vector<u8>;
```
第一个参数是 hash，第二个是 v,r,s 按照 Ethereum 的方式拼接在一起，返回 Ethereum address bytes，如果发生错误则返回空的 vector。
part of: #3013
> [vm] Implement native function ecrecover

- vm/compiler/src/dependency_order.rs
Fix dependency ordering missing module when a module use external modules.
```
module SafeMath {
use 0x1::Math;
use 0x1::Errors;
}
```
> fix node missing

- Cargo.lock
- account/api/src/rich_wallet.rs
- chain/Cargo.toml
- chain/api/Cargo.toml
- chain/api/src/chain.rs
- chain/api/src/lib.rs
- chain/service/src/chain_service.rs
- chain/src/chain.rs
- chain/tests/test_proof.rs
- commons/accumulator/src/accumulator_test.rs
- commons/accumulator/src/inmemory/accumulator_test.rs
- commons/accumulator/src/lib.rs
- commons/accumulator/src/proof/mod.rs
- contrib-contracts/src/starcoin_merkle_test.rs
- genesis/src/lib.rs
- state/api/src/chain_state.rs
- state/service/src/service.rs
- state/statedb/src/lib.rs
- storage/src/lib.rs
- storage/src/transaction_info/mod.rs
- vm/types/src/contract_event.rs
- vm/types/src/transaction/mod.rs
base on pr #3039 
TODO,将在后面的一系列 pr 中完成. 
1. 定义获取 transaction info proof 的 RPC 接口.
2. 当前获取 transaction info proof 需要 transaction 在全局的 accumulator 中的 index, 但尚未提供获取 txn 全局 index 的方法, 需要提供.
3. transaction info proof 同时可以包含 event proof 和 state proof, 但 state proof 当前尚不可用.
> [proof] Implement TransactionInfoWithProof

- commons/forkable-jellyfish-merkle/src/jellyfish_merkle_test.rs
- commons/forkable-jellyfish-merkle/src/node_type/mod.rs
- commons/forkable-jellyfish-merkle/src/proof.rs
- rpc/generated_rpc_schema/state.json
验证可以通过 non-existence proof 来计算出该节点写入后的新 root。
初步验证通过，需要增加更多测试。
> [merkle] Support compute root by non-existence proof and add a test

- .gitignore
- Cargo.lock
- vm/stdlib/Move.toml
- vm/stdlib/unit-test/Move.toml
- vm/stdlib/unit-test/sources/UnitTest.move
As unit test has to be Std module.
> make unit test as a package

- .gitattributes
Should make it nicer to review PR's and browse Move code on GitHub.
> [devex] add Move syntax highlighting on GitHub

- vm/stdlib/compiled/latest/doc/U256.md
- vm/stdlib/sources/U256.move
- Add `pragma opaque` to arithmetic functions that invoke native functions;
- Specification for them added (TODO: but doesn't seem to be used by MVP);
- `U256.md` updated.
> fix: stdlib U256 native function verification workaround

- vm/move-package-manager/src/compatibility_check_cmd.rs
- vm/move-package-manager/src/lib.rs
- vm/move-package-manager/src/main.rs
- vm/move-package-manager/src/releasement.rs
Add a command to check compatibility of package modules.
> mpm: provider compatibility check

- rpc/server/src/module/state_rpc.rs
if the resource format is not compatible with the Struct, just ignore the error, and do not return decoded resource.
> [rpc] Do not raise error when decode resource or resolve module failed

- .github/ISSUE_TEMPLATE/01_BUG_REPORT.md
- .github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- scripts/check_commit.sh
1. Add a script for fast check the commit.
2. Add Contribution Guide and Code of Conduct.
3. Add Issue and Pull request template.
> [doc] Improve contributing documents and add a script for check commit.

- config/src/storage_config.rs
- node/src/node.rs
rocksdb write IO error: Too many open files
-
-
-
> enlarge max_open_files

- commons/scmd/src/context.rs
When hitting `Ctrl-C`, wait for a new command input instead of quiting.
> Remove quiting action upon Ctrl-C

- cmd/starcoin/src/dev/package_cmd.rs
- vm/compiler/src/bytecode_transpose.rs
the `dev package` command should serialize the Move module with version 3 file format.
This commit has cherry-picked to branch release-v1.10, and release a new version: https://github.com/starcoinorg/starcoin/releases/tag/v1.10.1
> [cmd] `dev package` auto convert module to Move file format version 3.

- node/src/node.rs
- storage/src/db_storage/mod.rs
> fix starcoin_db_export apply open files limit

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
the Move changes at: 
https://github.com/starcoinorg/move/pull/2
Compatibility notes:
1. New CLI client can connect to old node RPC (json deserialize compatibility) 
2. But Old CLI client can not connect to the new RPC.
The following RPC APIs are mainly affected:
1. `account.sign_txn`
2. `txpool.submit_transaction`
The `scripts/import_net_block.sh` also affected, old data can be imported by new starcoin binary, but when exporting new json data, it can not be imported by old starcoin binary. 
-
-
-
> [move] Update move for fix StructTag json compatibility bug

- README.md
> [doc] Add code lines statistics to readme

- kube/manifest/runner/runner.yaml
when we do the cmd  
`kubectl apply -f runner.yaml
`
it will throw error msg like this:
`error validating data: [ValidationError(RunnerDeployment.spec.template.spec.resources): unknown field "dockerEnabled" in dev.summerwind.actions.v1alpha1.RunnerDeployment.spec.template.spec.resources, ValidationError(RunnerDeployment.spec.template.spec.resources): unknown field "dockerdContainerResources" in dev.summerwind.actions.v1alpha1.RunnerDeployment.spec.template.spec.resources, ValidationError(RunnerDeployment.spec.template.spec.resources): unknown field "dockerdWithinRunnerContainer" in dev.summerwind.actions.v1alpha1.RunnerDeployment.spec.template.spec.resources]; if you choose to ignore these errors, turn validation off with …
> fix manifest for action runner

- cmd/db-exporter/README.md
- cmd/db-exporter/src/main.rs
- scripts/import_snapshot.sh
- scripts/release.sh
add increment export snapshot
-
-
-
> add increment export snapshot

- kube/manifest/aws/cluster-autoscaler-policy.json
Current policy file not fits the lastest k8s autoscaler, cause it requires additional actions
Here are the related PR and ReadMe.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#iam-policy
https://github.com/kubernetes/autoscaler/pull/4468/files
> use recommended policy for lastest autoscaler

- chain/api/src/message.rs
- chain/api/src/service.rs
- chain/service/src/chain_service.rs
- chain/src/chain.rs
- chain/tests/test_block_chain.rs
- cmd/db-exporter/src/main.rs
- network-rpc/src/rpc.rs
- storage/src/block_info/mod.rs
- storage/src/cache_storage/mod.rs
- storage/src/db_storage/mod.rs
- storage/src/lib.rs
- storage/src/metrics.rs
- storage/src/storage.rs
- storage/src/tests/test_batch.rs
- storage/src/tests/test_storage.rs
- storage/src/transaction/mod.rs
- storage/src/transaction_info/mod.rs
use multi_get replace for loop
-
-
-
> use storage multi_get

- chain/src/verifier/mod.rs
- chain/tests/test_block_chain.rs
- commons/forkable-jellyfish-merkle/src/node_type/node_type_test.rs
- executor/src/account.rs
- sync/src/block_connector/test_illegal_block.rs
- vm/types/src/on_chain_config/mod.rs
fix code style and remove dup code
-
-
-
> remove clippy_vec_init_and_push and dup code

- kube/manifest/runner/runner.yaml
1. support cluster autoscaler scale to zero node, use k8s feature tolerations && taints
2. fix integration test timeout issue #3160
> runner config updated, enable integration test and scaler to zero ci nodes

- README.md
update --local-account-dir args to ~/.starcoin/main/account_vaults
-
-
-
> [doc] A small change to README

- vm/move-package-manager/src/compatibility_check_cmd.rs
- vm/move-package-manager/src/lib.rs
- vm/move-package-manager/src/main.rs
Issue Number: resolve #3308  fix #3229 
Use `mpm integration-test` to replace `mpm spectest`, and use the `tests` as tests files dir.
The `mpm spectest` command is still available for compatibility.
> [mpm] change the `spectest` to `integration-test`

- Cargo.lock
- commons/decrypt/Cargo.toml
- commons/decrypt/src/lib.rs
- vm/stdlib/Cargo.toml
Bump pbkdf2 from 0.3.0 to 0.11.0## Pull request type
Issue Number: #3318 
-
-
-
> Bump pbkdf2 from 0.3.0 to 0.11.0

- Cargo.lock
- contrib-contracts/src/starcoin_merkle_test.rs
- executor/src/block_executor.rs
- state/state-tree/Cargo.toml
- state/state-tree/src/state_tree.rs
- state/state-tree/src/state_tree_test.rs
merge transactions of block flush, improve performance
-
-
-
> Merge statedb flush

- account/src/account_test.rs
- cmd/merkle-generator/src/lib.rs
- cmd/miner_client/src/stratum_client_service.rs
- commons/logger/src/lib.rs
- commons/metrics/src/op_counters.rs
- config/src/tests.rs
- contrib-contracts/src/merkle_distributor_test.rs
- rpc/client/src/lib.rs
- rpc/middleware/src/lib.rs
- state/state-tree/src/state_tree.rs
- storage/src/tests/test_block.rs
- sync/src/block_connector/write_block_chain.rs
- sync/src/tasks/mod.rs
- types/src/block.rs
- vm/move-coverage/src/bin/coverage-summaries.rs
- vm/move-coverage/src/bin/source-coverage.rs
- vm/move-package-manager/src/releasement.rs
- vm/move-prover/tests/testsuite.rs
- vm/natives/src/bcs.rs
- vm/natives/src/signature.rs
- vm/types/src/event.rs
- vm/types/src/token/token_code.rs
- vm/types/src/token/token_value.rs
- vm/types/src/transaction/tests.rs
- vm/types/src/unit_tests/access_path_test.rs
Issue Number: #3336
N/A
[P.NAM.08 避免在变量的命名中添加类型标识](https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/safe-guides/code_style/naming/P.NAM.08.html#pnam08--%E9%81%BF%E5%85%8D%E5%9C%A8%E5%8F%98%E9%87%8F%E7%9A%84%E5%91%BD%E5%90%8D%E4%B8%AD%E6%B7%BB%E5%8A%A0%E7%B1%BB%E5%9E%8B%E6%A0%87%E8%AF%86)
Variable naming containing `bytes` and `str` still exists in the project. Mainly because the Rust Analyzer code refactoring tool did not work properly in these cases, and I myself was not familiar with the code context, so I decided not to make changes for now.
> [refactor] Improve variable naming convention

- vm/move-package-manager/src/compatibility_check_cmd.rs
> [mpm] Fix #3325

- vm/move-package-manager/src/lib.rs
-
-
-
https://github.com/starcoinorg/starcoin-framework/runs/6058959721?check_suite_focus=true
> [mpm] use `integration-tests` rather than `tests`, for avoid conflict with `mpm package test`

- .github/workflows/sync_blocks.yml
- scripts/sync_block_main.py
Add github cron workflow for sync blocks
> sync block cron

- cmd/miner_client/src/stratum_client_service.rs
> Fix stratum client issue

- vm/starcoin-transactional-test-harness/src/lib.rs
Support:
```
init -n dev --public-keys AKey=0x07d815b1ef166cbba8dc80e6e2f0e50e3461551ca118a6587632e615123139a6 BKey=0x3517cf661eb9ec48ad86639db66ea463b871b7d10c52bb37461570aef68f8c36 
```
and
```
init -n dev --public-keys AKey=0x07d815b1ef166cbba8dc80e6e2f0e50e3461551ca118a6587632e615123139a6 --public-keys BKey=0x3517cf661eb9ec48ad86639db66ea463b871b7d10c52bb37461570aef68f8c36 
```
-
-
-
https://discord.com/channels/822159062475997194/892760287797714954/966563936331776050
> [mpm] Fix integration tests `public_keys` arguments

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
1. Upgrade Move repo to https://github.com/move-language/move
2. Pickup Fix the bug that move-disassembler panicked for using wrong type_param_context when handling generic types ([#49](https://github.com/move-language/move/pull/49))
3. Pickup [repo] Remove workspace hack. ([#55](https://github.com/move-language/move/pull/55)) 
Diff view:
https://github.com/starcoinorg/move/compare/0b4655469084eb2fb6b8a6a7690342d767f05e5b..2e8f03e7bb24e49dbe807bcfc0c32c4f605bba71
> [move] Update move dep

- .github/workflows/sync_blocks.yml
Once a day is not enough for sync blocks task while block gap is set to 10k.
Twice a day should be ok.
> modify sync blocks timing

- vm/move-package-manager/src/main.rs
> fix typo of help information of `mpm check-compatibility`

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
Pickup https://github.com/move-language/move/pull/90 for support Windows 
Issue Number: #3130
-
-
-
> [move] Update move dependency for Windows support

- cmd/starcoin/src/account/submit_txn_cmd.rs
- cmd/starcoin/src/dev/get_coin_cmd.rs
- cmd/starcoin/src/view.rs
> Increase the interpretation of black words

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
Pickup https://github.com/move-language/move/pull/116 and update move dependency
Issue Number: #3130
-
-
-
> [move] Update move dependency for fix invalid character for tab.

- scripts/dev_setup.sh
- [x ] Bugfix
Issue Number: #3410 
- detect by release first
port from https://github.com/move-language/move/pull/146
> [dev] improve package manager detection mechanism

- consensus/cryptonight-rs/build.rs
- scripts/dev_setup.sh
differentiate gcc-powerpc-linux-gnu package name on different
architecture
-
-
-
> differentiate gcc-powerpc-linux-gnu package name on different architecture

- commons/scmd/src/context.rs
Signed-off-by: Xuanwo <github@xuanwo.io>
Fix #3423 
```shell
:) ./target/debug/starcoin_generator --version
2022-05-31T20:52:52.593489944+08:00 ERROR - error: starcoin 1.11.10 (build:v1.11.9-alpha-20-ga43584bfc-dirty)
```
Issue Number: #3423 
`--version`:
```shell
:) ./target/debug/starcoin_generator --version
starcoin 1.11.10 (build:v1.11.9-alpha-20-ga43584bfc-dirty)
```
`-h`
```shell
:) ./target/debug/starcoin_generator -h
starcoin 1.11.10
Starcoin
USAGE:
starcoin_generator [OPTIONS] [SUBCOMMAND]
...
```
None.
> fix(scmd): Fix messages printed as error wrongly

- vm/starcoin-transactional-test-harness/src/lib.rs
Support set MultiSig public key in integration test init args
> [mpm] Integration test support multi sign address

- cmd/starcoin/src/main.rs
check ipc status before run node
do necessary clean work
Fix issue https://github.com/starcoinorg/starcoin/issues/3456
program terminate will error such as "Connection refused (os error 111)"
Issue Number:  https://github.com/starcoinorg/starcoin/issues/3456
It will try to connect .ipc before run_node_by_opt, and if it's not connectable, will try to remove the broken .ipc
> check ipc status before run node and remove the .ipc file if necessary

- abi/resolver/src/lib.rs
- rpc/api/src/contract_api.rs
- rpc/generated_rpc_schema/contract_api.json
- rpc/server/src/module/contract_rpc.rs
Related #3450.
Issue Number:  #3450.
- Add an new RPC API that could resolve function index from CompiledModule.
- Here is an example invocation in my own environment(deployed a toy [mycounter](https://github.com/starcoinorg/starcoin-cookbook/tree/main/examples/my-counter) contract)
```shell
$ curl 'http://localhost:9850/' -X POST -H 'Content-Type: application/json' --data-raw '{"method":"contract.resolve_module_function_index","params":["0x43c83253e82b2667760caa005bfe4e36::MyCounter", 0],"id":56,"jsonrpc":"2.0"}'
```
- The result I got
```json
{
"jsonrpc": "2.0",
"result": {
"args": [
{
"doc": "",
"name": "p0",
"type_tag": {
"Reference": [
false,
"Signer"
]
}
}
],
"doc": "",
"module_name": {
"address": …
```
> [rpc] add RPC API contract.resolve_module_function_index

- cmd/peer-watcher/src/main.rs
- network-p2p/src/protocol/event.rs
- network-p2p/src/service.rs
- network-p2p/src/service_test.rs
- network/api/src/tests.rs
- network/src/service.rs
- network/src/worker.rs
- rpc/api/src/types.rs
- rpc/generated_rpc_schema/node.json
- sync/src/tasks/mock.rs
- sync/src/tasks/tests.rs
- types/src/peer_info.rs
Issue Number: #3439 
- Retrieve `client_version` and set it to a field `version_string` of `PeerInfo` while handshaking in `network-p2p`.
- Add a field `version_string` to `PeerInfoView` to return `version_string` in `node.peers` RPC invocation.
> [network] add version_string field to PeerInfo 

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
https://github.com/starcoinorg/starcoin/issues/3355
-
-
-
> fix the wrong logic in VMStatus::status_code() pick up move-language#197

- miner/src/lib.rs
- rpc/server/src/module/debug_rpc.rs
- types/src/system_events.rs
- vm/types/src/time.rs
Add `GenerateSleepBlockEvent` to generate empty block by `dev sleep` command without check `disable-mint-empty-block`. To fix `dev sleep` command didn't update on chain timestamp.
As the `disable_mint_empty_block` flag is true in Dev network, and the `dev sleep` command just trigger it to update on chain timestamp, then eventually, the `dev sleep` command didn't update on chain timestamp.
Issue Number: #3329
- Add an new event `GenerateSleepBlockEvent` that will add block directly without check `disable_mint_empty_block`
Result of `chain info` before `dev sleep`:
<details><summary>Click to expand/collapse</summary>
```json
{
"ok": {
"block_info": {
"block_accumulator_info": {
"accumulator_root": …
```
> [dev] fix dev sleep command do not update on chain timestamp

- Cargo.lock
- cmd/faucet/Cargo.toml
- cmd/faucet/src/web.rs
- commons/metrics/Cargo.toml
hyper, tiny_http, rust_embed fix potential security upgrade
-
-
-
> fix some dependabot alter

- cmd/starcoin/src/chain/get_block_cmd.rs
- rpc/api/src/chain/mod.rs
- rpc/api/src/types.rs
- rpc/generated_rpc_schema/chain.json
- rpc/server/src/module/chain_rpc.rs
- rpc/server/src/module/pubsub.rs
Issue Number: #3479 
- Add `raw` field into `GetBlockOption` to support specify it to get raw block
- Add optional `raw` field into `BlockView` and fill it when above field is set to true.
> [rpc] add raw field into BlockView to support get raw block

- .github/workflows/ci_monitor_scaler.yml
- scripts/monitor_autoscaler_recreate.py
the autoscaler of ci nodes will not response the scale event, when it was recreated.
we monitor the ci node, if it had been recreated, trigger the scale event to 1 node, everything will be fine then. if the node idle for a while, it will be automaticlly scale to 0.
> add monitor for ci autoscaler

- Cargo.lock
- account/api/src/provider.rs
- account/provider/Cargo.toml
- account/provider/src/lib.rs
- account/provider/src/private_key_provider.rs
- account/provider/src/provider/mod.rs
- cmd/starcoin/src/account/import_cmd.rs
- cmd/starcoin/src/dev/mod.rs
- config/src/account_provider_config.rs
- vm/move-package-manager/Cargo.toml
- vm/move-package-manager/src/deployment.rs
- vm/move-package-manager/src/lib.rs
- vm/move-package-manager/src/main.rs
Issue Number: #3462 
- Add `mpm deploy` subcommand.
Draft 版本，目前已经将 `starcoin dev deploy` 命令的功能移植到 `mpm deploy`。 使用命令如下：
```
mpm deploy --rpc ws://127.0.0.1:9871 --local-account-dir ~/.starcoin/main/account_vaults/ --password xxxx /path/to/package
```
考虑到 mpm 不应该过度依赖 starcoin node，因此只支持 rpc 链接； 因为需要签名，所以需要 account 已经 password 来unlock 账号。也许将这些 rpc 参数放到一个配置文件， 将密码参数放到一个 .secret 文件中更方便一点？
是否有其他的需求和建议？ @jolestar @WGB5445
> add mpm deploy subcommand

- Cargo.lock
- commons/scmd/Cargo.toml
- commons/scmd/src/console.rs
- commons/scmd/src/context.rs
- commons/scmd/src/lib.rs
Issue Number: #3247 
- In console mode, auto-completion for command, subcommand and file path is supported.
> support auto-completion for console cmd

- cmd/starcoin/src/dev/deploy_cmd.rs
When i want to deploy the module for the Dao account, the module cannot be deployed normally because the sender and the sender in the blob are different.
> Fix #3527 allow dev deploy deploy the package to another address

- cmd/airdrop/src/main.rs
> [tools] Improve airdrop tools

- scripts/import_snapshot.sh
- [ x] Bugfix
```
Error: No such file or directory (os error 2)
apply-snapshot main /snapshot fail
```
- no this error
-
-
> [fix] fix snapshot path  in import_snapshot.sh

- cmd/starcoin/src/dev/dev_helper.rs
- vm/move-package-manager/src/compatibility_check_cmd.rs
Add a --pre-modules option to mpm check-compatibility to check compatibility between the current version and the previous version.
usage: 
`mpm check-compatibility --pre-modules release/BasicCoin.v0.0.0.blob/BasicCoin.v0.0.0.blob`
> pre-version compatibility check

- cmd/db-exporter/src/main.rs
Issue Number: https://github.com/starcoinorg/starcoin/issues/3539
-
-
-
need modify scripts/sync_block.py。It's describe in https://github.com/starcoinorg/starcoin/issues/3539  @yourmoonlight
> add import snapshot file lines num check

- kube/manifest/starcoin-halley.yaml
- kube/manifest/starcoin-proxima.yaml
update_move branch deploy to halley
-
-
-
> deploy update_move branch to proxima

- scripts/sync_block.py
Currently, we are syncing the blocks using a cron action.
Sometimes, the export behavior did not work as expected.
For example, we would like to export blocks from 6865515 to 6875514, but the export cmd export from 6865515 to 6875106.
The  export behavior will be consistent.
https://github.com/starcoinorg/starcoin/issues/3556
https://github.com/starcoinorg/starcoin/issues/3549
> fix_sync_block with 1000 block gap

- scripts/sync_block.py
Currently the export snapshot process may be failed for some unknown reason,  so we should add some check logic to make the snapshot is correct for sure.
https://github.com/starcoinorg/starcoin/issues/3539
> check export snapshot status with the manifest file

- .github/workflows/sync_blocks.yml
- scripts/dev_setup.sh
- scripts/sync_block.py
> fix sync snapshot scripts and add workflow_dispatch event trigger

- .github/workflows/auto_bump_homebrew.yml
Currently it needs to be updated manually
https://github.com/starcoinorg/starcoin/issues/3547
> Auto bump homebrew formula

- cmd/starcoin/src/dev/get_coin_cmd.rs
> cli: dev get-coin don't check account

- Cargo.lock
- cmd/starcoin/src/cli_state.rs
- vm/dev/Cargo.toml
- vm/dev/src/playground.rs
- vm/vm-runtime/src/starcoin_vm.rs
1. 在 cli 中执行 dry run，状态通过 remote state reader 获取，虚拟机在 cli 中执行，方便 debug。
2. 交易执行失败后打印 WARN 日志，但方便排查问题。
```
starcoin --connect ws://barnard.seed.starcoin.org:9870 --local-account-dir ~/.starcoin/barnard/account_vaults  dev deploy --dry-run package.blob
```
> [cli] dry run at cli side and print warn log when transaction execute failed

- Cargo.lock
- cmd/starcoin/src/account/execute_script_cmd.rs
- cmd/starcoin/src/account/execute_script_function_cmd.rs
- cmd/starcoin/src/account/sign_multisig_txn_cmd.rs
- cmd/starcoin/src/dev/package_cmd.rs
- cmd/starcoin/src/dev/tests.rs
- commons/scmd/Cargo.toml
- commons/scmd/src/context.rs
- commons/scmd/src/result.rs
- rpc/api/src/types.rs
- testsuite/Cargo.toml
- testsuite/features/cmd.feature
- testsuite/tests/integration.rs
- testsuite/tests/steps/cmd.rs
- testsuite/tests/steps/compat.rs
- types/src/lib.rs
Issue Number: resolve #3576 
```
starcoin% chain list-block
starcoin% chain get-block {{$.chain[0].ok[0].block_hash}}
```
https://github.com/starcoinorg/starcoin/blob/23e9c6d423c50ab7cfed9233ca23b4ff903aa6f0/testsuite/features/cmd.feature#L186-L194
@baichuan3 @WGB5445 可以暂时用这种方式来测试 Checkpoint 这样的合约
> [scmd]Support jpst template expression in command line and starcoin testsuit

- .cargo/config
- vm/transaction-builder-generator/README.md
- vm/transaction-builder-generator/examples/cpp/stdlib_demo.cpp
- vm/transaction-builder-generator/examples/java/StdlibDemo.java
- vm/transaction-builder-generator/src/dart.rs
- vm/transaction-builder-generator/src/generate.rs
- vm/transaction-builder-generator/src/java.rs
- vm/transaction-builder-generator/src/python3.rs
- vm/transaction-builder-generator/src/rust.rs
- vm/transaction-builder-generator/tests/installer.rs
> [transaction-builder-generator] fix package name for Java and change diem to startcoin, and update readme

- kube/manifest/starcoin-halley.yaml
```
2022-08-04T14:22:25.316825891+00:00 INFO - Check genesis file.
2022-08-04T14:22:25.318105457+00:00 ERROR - GenesisVersionMismatch { expect: HashValue(0x356200ff41aadc53c5c33ef963665aa8aa8fb23df749494edabcbeadf48c49de), real: HashValue(0x70df244aa17960420a7c131d268df36040a04299868746d8f6d386f7d9d4c08f) }, please clean your data dir.
bash: line 1:    11 Segmentation fault      (core dumped) /starcoin/starcoin -n halley -d /sc-data --discover-local=true $node_key_flag
Node start fail, try to remove config.
```
genesis reset 的情况下发生 core dumped，无法正常清理数据，所以修改为发生错误直接清理数据。
> [genesis] update k8s config for halley, ensure clear data

- vm/vm-runtime/src/starcoin_vm.rs
Execute readonly function do not check gas
Check gas when calling a readonly function, and avoid malicious use of call readonly function.
> [vm] check gas when execute readonly function

- Cargo.lock
- cmd/merkle-generator/Cargo.toml
remove Cargo.lock rust-crypto for security
- [] Build related changes
remove https://github.com/starcoinorg/starcoin/security/dependabot/20
-
-
-
> update dependency merkletree remove rust-crypto

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- devtools/x/Cargo.toml
- vm/compiler/Cargo.toml
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/starcoin-transactional-test-harness/src/context.rs
- vm/starcoin-transactional-test-harness/src/fork_state.rs
- vm/starcoin-transactional-test-harness/src/lib.rs
- vm/starcoin-transactional-test-harness/src/remote_state.rs
- vm/stdlib/Cargo.toml
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
Issue Number: resolve #3574 
-
-
-
https://github.com/starcoinorg/move/pull/11
TODO: 测试用例
> [mpm] Integration test support package and deploy command

- config/src/account_provider_config.rs
add serde default for AccountProviderConfig's field named from_env
Issue Number: https://github.com/starcoinorg/starcoin/issues/3630
backward to old version of config.toml
> add backward compatibility for AccountProviderConfig

- vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd_halley.exp
- vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd_halley.move
- vm/starcoin-transactional-test-harness/tests/cases/package_deploy_cmd.exp
- vm/starcoin-transactional-test-harness/tests/cases/package_deploy_cmd.move
> [mpm] add some integration test

- rpc/api/src/state/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/state_rpc.rs
> [rpc] suport short address

- sync/src/block_connector/block_connector_service.rs
> clean some debug info

- cmd/miner_client/src/main.rs
> miner_client: Update default connection port

- cmd/starcoin/src/state/list_cmd.rs
- testsuite/features/cmd.feature
> [cli]list resource support filter struct_type and start_idx max_size

- rpc/api/src/types.rs
- rpc/client/src/lib.rs
add some rpc-api and convert to help mini-starcoin
> [types] Some useful  function for type convert and add `get_state_node_by_node_hash` to RPCClient

- scripts/auto_rerun_test.ps1
- scripts/auto_rerun_test.sh
Issue Number: fix #3659 
-
-
-
first commit is expected to fail in *build and test* phase
> [ci][fix] make `cargo xtest` no-fail-fast

- vm/starcoin-transactional-test-harness/src/context.rs
- vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd.exp
- vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd.move
Must flush state tree after state tree change, otherwise, get state proof will raise the error `Missing node at HashValue`
> [mpm] Fix mpm integration test call api state.get_with_proof_by_root_raw

- Cargo.lock
- cmd/merkle-generator/Cargo.toml
use maintained memmap2
address https://github.com/starcoinorg/starcoin/issues/2403
-
-
-
> [dep][security] bump filecoin-project/merkletree, remove memmap

- vm/starcoin-transactional-test-harness/src/lib.rs
- mpm faucet 输出交易信息和结果，可以用来获取相关信息，比如获取接受 faucet 的地址。`$.faucet[0].txn.raw_txn.decoded_payload.ScriptFunction.args[0]`
> add faucet output as var context

- vm/starcoin-transactional-test-harness/src/lib.rs
当前代码会尝试将 Discard txn 添加到 txn_accumulator 中，而 txn_accumulator 只接受 KeptVMStatus 的 txn，因此在 check 时遇到了 Discard 的 txn， 从而发生 panic 。
-  Bug fixed
相关 issue： https://github.com/starcoinorg/starcoin-framework/pull/95#issuecomment-1229125780
> mpm integration-test: fix discarded txn

- .github/workflows/codecov.yml
- genesis/tests/generated_files.rs
- scripts/coverage_report.sh
- x.toml
Issue Number: #3666
- the `core dump` mention in #3666 is hard to deal with and it's using debug info to collect cov data, so maybe use another approach to collect coverage info
- use `cargo llvm-cov` to gen coverage info
-
> [code-coverage] use `cargo llvm-cov` to generate coverage info

- account/api/src/types.rs
- account/src/account.rs
- account/src/account_manager.rs
- account/src/account_test.rs
- rpc/generated_rpc_schema/account.json
Add lock status display for account show command. Try to fix [#3690](https://github.com/starcoinorg/starcoin/issues/3690)
> Add lock display for account show

- consensus/cryptonight-rs/ext/oaes_lib.c
Issue Number: fix #3709 
-
-
-
> fix `ftime` warning

- vm/starcoin-transactional-test-harness/src/lib.rs
- vm/starcoin-transactional-test-harness/tests/cases/content.json
- vm/starcoin-transactional-test-harness/tests/cases/var.exp
- vm/starcoin-transactional-test-harness/tests/cases/var.move
Issue Number: resolve #3711
- mpm integration-test add two new directives: `var` and `read-json`.
- `var` can be used to set global variable, cmd: `//# var <key1>=<value1> <key2>=<value2> ...`
- `read-json` can read json content from local file, cmd: `//# read-json <file_path>`
- usage example:
```
//# init -n dev
//# faucet --addr creator --amount 12345000000
//# read-json tests/cases/content.json
//# var a=123 addr={{$.faucet[0].txn.raw_txn.decoded_payload.ScriptFunction.args[0]}}
//#run --signers creator --args {{$.var[0].a}}u64 --args {{$.var[0].addr}}
script {
use StarcoinFramework::Debug;
fun main(_sender: signer, number: u64, addr: address) {
Debug::print(&number);
Debug::print(&addr);
}
}
```
> add var and read_json in mpm integration-test

- Cargo.lock
- cmd/db-exporter/Cargo.toml
- cmd/db-exporter/src/lib.rs
- cmd/db-exporter/src/main.rs
- scripts/verify_modules.sh
Add verify-modules command to db_exporter for fast verify all modules in transactions.
-
-
-
> [db-exporter] Add verify-modules command for fast verify modules

- sync/src/tasks/tests.rs
Issue Number: https://github.com/starcoinorg/starcoin/pull/3741#issuecomment-1250615387
-
-
-
single threaded test time on local machine：
test_full_sync_continue 78.52s
test_full_sync_fork_from_genesis 64.57s
> [test] larger timeout on `full_sync` test

- genesis/src/lib.rs
- vm/move-package-manager/src/lib.rs
- vm/starcoin-transactional-test-harness/src/context.rs
- vm/starcoin-transactional-test-harness/src/lib.rs
- vm/stdlib/src/lib.rs
- vm/transaction-builder/src/lib.rs
- mpm 集成测试时，如果当前项目是 starcoin-framework， 可以指定 `--load-stdlib` 选项，将当前项目作为 stdlib 覆盖 mpm 原本的 stdlib。`mpm integration-test --ub --load-stdlib`
在 [starcoin-framework master](https://github.com/starcoinorg/starcoin-framework/tree/d2c4f5c28d97dbe856fcbc4bf0a39bb4bfa362b1) 上测试时，遇到三个失败的测试用例：
1. [starcoin_upgrade_module](https://github.com/starcoinorg/starcoin-framework/blob/d2c4f5c28d/integration-tests/starcoin_dao/starcoin_upgrade_module.move) 和 [starcoin_onchain_config](https://github.com/starcoinorg/starcoin-framework/blob/d2c4f5c28d/integration-tests/starcoin_dao/starcoin_onchain_config.move) 是因为修改了 StarcoinDAO 的 proposal config，更新测试代码即可；
2.  [dao_upgrade_incompatible](https://github.com/starcoinorg/starcoin-framework/blob/d2 …
> mpm support load stdlib dynamically

- .github/workflows/docker_build.yml
- docker/Dockerfile
Issue Number: fix #3770 
-
-
-
> [dev]Update docker_build.yml docker/setup-buildx-action to 2,  Dockerfile rustup version to 1.25.1

- cmd/starcoin/src/cli_state.rs
- cmd/starcoin/src/view.rs
- testsuite/features/cmd.feature
> Add gas token to transaction options

- Cargo.lock
- abi/decoder/Cargo.toml
- abi/resolver/Cargo.toml
- abi/resolver/src/lib.rs
- cmd/db-exporter/Cargo.toml
- cmd/starcoin/Cargo.toml
- commons/proptest-helpers/Cargo.toml
- executor/Cargo.toml
- test-helper/Cargo.toml
- vm/compiler/Cargo.toml
- vm/compiler/src/lib.rs
- vm/move-coverage/Cargo.toml
- vm/move-explain/Cargo.toml
- vm/move-package-manager/Cargo.toml
- vm/move-package-manager/src/compatibility_check_cmd.rs
- vm/move-prover/Cargo.toml
- vm/natives/Cargo.toml
- vm/resource-viewer/Cargo.toml
- vm/starcoin-transactional-test-harness/Cargo.toml
- vm/stdlib/Cargo.toml
- vm/stdlib/src/main.rs
- vm/transaction-builder-generator/Cargo.toml
- vm/types/Cargo.toml
- vm/vm-runtime/Cargo.toml
- vm/vm-runtime/tests/test_native_functions.rs
use simply method same with https://github.com/starcoinorg/starcoin/pull/3817
-
-
-
> revert code and use new method to fix publish_module_bundle crash

- Cargo.lock
- chain/api/src/chain.rs
- chain/api/src/message.rs
- chain/api/src/service.rs
- chain/service/src/chain_service.rs
- chain/src/chain.rs
- chain/tests/test_block_chain.rs
- cmd/starcoin/src/chain/list_block_cmd.rs
- config/src/lib.rs
- rpc/api/generated_rpc_schema/chain.json
- rpc/api/src/chain/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/chain_rpc.rs
- scripts/nextest.sh
- testsuite/Cargo.toml
- testsuite/tests/steps/sync.rs
- vm/starcoin-transactional-test-harness/src/fork_chain.rs
> [Feature] RPC blocks support positive sequence

- Cargo.lock
- Cargo.toml
- rpc/api/Cargo.toml
- rpc/api/src/account/mod.rs
- rpc/api/src/chain/mod.rs
- rpc/api/src/contract_api.rs
- rpc/api/src/debug/mod.rs
- rpc/api/src/generate_schema.rs
- rpc/api/src/miner.rs
- rpc/api/src/network_manager.rs
- rpc/api/src/node/mod.rs
- rpc/api/src/node_manager.rs
- rpc/api/src/state/mod.rs
- rpc/api/src/sync_manager.rs
- rpc/api/src/txpool/mod.rs
Remove the patch version of jsonrpc
Use the [openrpc-dervice](https://github.com/starcoinorg/openrpc-rs) to implement the proc macro
-
-
-
> Refactor openrpc

- Cargo.lock
- executor/Cargo.toml
- executor/tests/script_function_test.rs
https://github.com/starcoinorg/move/pull/49
add struct republish backward incompatible test
-
-
-
> add struct republish backward incompatible test

- Cargo.lock
- Cargo.toml
fix io-lifetimes compiler error
-
-
-
> remove typemap and fix io-lifetimes compiler error

- kube/manifest/starcoin-barnard.yaml
- kube/manifest/starcoin-proxima.yaml
> update starcoin-proxima.yaml and starcoin-barnard.yaml

- vm/move-package-manager/src/package.rs
- vm/move-package-manager/src/release.rs
```shell
mpm package new hello
```
change Move.toml.
previous mpm  version 1.12.5, print output
```toml
[package]
name = "hello"
version = "0.0.0"
```
we want to change it 
```toml
[package]
name = "hello"
version = "0.0.0"
[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "main" }
[addresses]
StarcoinFramework =  "0x1"
```
-
-
-
> change mpm package new Move.toml and fix mpm release

- vm/vm-runtime/src/natives.rs
> Fix move unittest error

- scripts/upload_block_on_s3.sh
- scripts/upload_file_any_size.py
> add upload file any size

- Cargo.lock
- Cargo.toml
…eck_disk_space, Upgrade sysinfo library from 0.25.1 to 0.29.0
When running Starcoin, the `BlockConnectorService` periodically sends a BlockDiskCheckEvent message in the started callback. In this particular case, the older version(0.25.1) of systeminfo mistakenly releases the system object one extra time, leading to a crash. This issue occurs specifically at line 56 in [block_connect_service.rs](https://github.com/starcoinorg/starcoin/blob/master/sync/src/block_connector/block_connector_service.rs#L56)
> Crashes on Apple Silicon M1 while start starcoin

- cmd/starcoin/src/dev/subscribe_cmd.rs
- cmd/starcoin/src/lib.rs
Issue Number:  #2188 
- add new subcommand to `starcoin dev subscribe` cli
```
starcoin% dev subscribe -h
dev-subscribe
Subscribe the chain events
USAGE:
dev subscribe [SUBCOMMAND]
OPTIONS:
-h, --help    Print help information
SUBCOMMANDS:
new_mint_block
new_block
event              Subscribe chain event
new_pending_txn
help               Print this message or the help of the given subcommand(s)
starcoin% dev subscribe new_mint_block
Subscribe successful, Press `q` and Enter to quit
{"parent_hash":"0xca6e753bf6f62531c7946f5b01d6e96c34fba2ecaaec975370eb0cdcbd44d13c","strategy":{"type":"CryptoNight"},"minti                                     ng_blob":"17c420f505b88d3c21a8d7b36bf633f807fd1c88c5f0e921cbaeb47e30fef2040000000000000000000000000 …
```
> starcoin cli supports subscribing NewMintBlock event

- executor/src/executor.rs
- vm/dev/src/playground.rs
- vm/types/src/on_chain_config/mod.rs
- vm/types/src/state_view.rs
- vm/vm-runtime/src/data_cache.rs
- vm/vm-runtime/src/starcoin_vm.rs
> [vm] StarcoinVM refactor remove mut reference for some functions

- Cargo.lock
- network-rpc/Cargo.toml
- network-rpc/api/src/lib.rs
- network-rpc/api/src/remote_chain_state.rs
- network-rpc/src/rpc.rs
- rpc/api/generated_rpc_schema/state.json
- rpc/api/src/state/mod.rs
- rpc/api/src/types.rs
- rpc/client/src/lib.rs
- rpc/client/src/remote_state_reader.rs
- rpc/server/src/module/state_rpc.rs
- state/api/src/chain_state.rs
- state/api/src/lib.rs
- state/api/src/message.rs
- state/api/src/mock/mock_chain_state_service.rs
- state/service/src/service.rs
- state/state-store-api/Cargo.toml
- state/state-store-api/src/lib.rs
- state/state-tree/src/mock/mod.rs
- state/statedb/src/lib.rs
- storage/src/lib.rs
- vm/starcoin-transactional-test-harness/src/fork_state.rs
> Feat tableinfo rpc

- Cargo.lock
- cmd/starcoin/src/dev/concurrency_level_cmd.rs
- cmd/starcoin/src/lib.rs
- network/src/service.rs
- rpc/api/generated_rpc_schema/debug.json
- rpc/api/src/debug/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/debug_rpc.rs
- scripts/nextest.sh
- vm/e2e-tests/Cargo.toml
- vm/transaction-benchmarks/Cargo.toml
> add set-get concurrency level cmd

- node/src/node.rs
- storage/src/chain_info/mod.rs
- storage/src/storage.rs
- storage/src/upgrade.rs
- types/src/startup_info.rs
> rollback chain head

- chain/open-block/src/lib.rs
- chain/src/verifier/mod.rs
- storage/src/upgrade.rs
> miner: Excluded transactions from blacklisted addresses during create block template

- cmd/starcoin/src/account/verify_sign_cmd.rs
- commons/accumulator/src/node_index.rs
- network-p2p/src/protocol/event.rs
- network/src/service.rs
- scripts/sync_block.py
- vm/compiler/src/dependency_order.rs
- vm/e2e-tests/src/account.rs
- vm/mvhashmap/src/unit_tests/mvhashmap_test.rs
- vm/parallel-executor/src/executor.rs
- vm/parallel-executor/src/scheduler.rs
- vm/parallel-executor/src/txn_last_input_output.rs
- vm/types/src/on_chain_config/gas_schedule.rs
- vm/types/src/transaction/authenticator.rs
- vm/types/src/unit_tests/access_path_test.rs
- workspaceify.py
> fix some comments

- Cargo.lock
- cmd/db-exporter/Cargo.toml
- cmd/db-exporter/src/main.rs
> db exporter add token supply command

- commons/forkable-jellyfish-merkle/src/node_type/mod.rs
- commons/metrics/src/op_counters.rs
- vm/parallel-executor/src/scheduler.rs
> chore: fix typos

- scripts/upload_file_any_size.py
…ation/api/latest/guide/s3.html
-
-
-
> use boto3 Multipart transfers

- flexidag/src/reachability/inquirer.rs
- flexidag/src/reachability/mod.rs
- flexidag/tests/tests.rs
- storage/src/block/mod.rs
- storage/src/lib.rs
- storage/src/upgrade.rs
- sync/src/tasks/block_sync_task.rs
Flexidag block synchronization improvements:
1, Optimized synchronization complexity, reduced from O(k*n) to O(n), where k is the number of block parents.
2, Reduced network requests for block synchronization.
3, Fixed reentrancy errors in reachability.
-
-
-
> optimization for the sync

- flexidag/src/blockdag.rs
- flexidag/src/consensusdb/consensus_relations.rs
- flexidag/src/consensusdb/db.rs
- flexidag/src/ghostdag/mergeset.rs
- flexidag/src/ghostdag/protocol.rs
- flexidag/tests/tests.rs
- network/tests/network_service_test.rs
> [FlexiDag]Add read-write lock in dag db store

- chain/open-block/src/lib.rs
- vm/transaction-builder/src/lib.rs
- vm/types/src/block_metadata/mod.rs
> [FlexiDag] remove some proxima-compatible codes

- block-relayer/src/block_relayer.rs
- sync/src/block_connector/block_connector_service.rs
- sync/src/block_connector/write_block_chain.rs
- types/src/system_events.rs
The dag block will not be broadcast if its block info's total difficulty is less than the header of the main, leading to an error: a new block that uses it as its one of parents will fail to be executed until the sync pull it.
```rust
pub fn select_head(&mut self, new_branch: BlockChain) -> Result<()> {
let executed_block = new_branch.head_block();
let main_total_difficulty = self.main.get_total_difficulty()?;
let branch_total_difficulty = new_branch.get_total_difficulty()?;
let parent_is_main_head = self.is_main_head(&executed_block.header().parent_hash());
if branch_total_difficulty > main_total_difficulty {
let (enacted_count, enacted_blocks, retracted_count, retracted_blocks) =
if !parent_is_main_head {
self.find_ancestors_from_accumulator(&new_branch)?
} else {
(1, …
```
> Broadcast dag block in any condition

- chain/src/chain.rs
- config/src/genesis_config.rs
- miner/Cargo.toml
- miner/src/create_block_template/mod.rs
- miner/tests/miner_test.rs
- sync/src/block_connector/block_connector_service.rs
- sync/src/block_connector/mod.rs
- sync/src/block_connector/write_block_chain.rs
- test-helper/src/txpool.rs
> add block_connector_service to miner

- chain/src/chain.rs
- chain/src/verifier/mod.rs
- sync/src/block_connector/write_block_chain.rs
- sync/src/tasks/block_sync_task.rs
> Check dag parents' existence

- cmd/starcoin/src/account/verify_sign_cmd.rs
- vm/framework/starcoin-framework/doc/account.md
- vm/framework/starcoin-framework/sources/account.move
> fix verify-signed-message

- vm/framework/starcoin-framework/doc/account.md
- vm/framework/starcoin-framework/doc/dao.md
- vm/framework/starcoin-framework/doc/stc_block.md
- vm/framework/starcoin-framework/doc/stc_transaction_validation.md
- vm/framework/starcoin-framework/sources/account.move
- vm/framework/starcoin-framework/sources/stc/stc_block.move
- vm/framework/starcoin-framework/sources/stc/stc_transaction_validation.move
- vm/framework/starcoin-framework/sources/stc/vm_config.move
> [compiler-v2] fixed authentication key  process on prologue and eilprologue

- Cargo.lock
- scripts/nextest.sh
- vm/framework/src/extended_checks.rs
- vm/framework/src/module_metadata.rs
- vm/vm-runtime/Cargo.toml
- vm/vm-runtime/tests/test_native_functions.rs
* add bytecode_instrcution attr to runtime metadata
-
-
-
> fix test-native-functions

- Cargo.lock
- cmd/merkle-generator/README.md
- contrib-contracts/Cargo.toml
- contrib-contracts/modules/EthStateVerifier.move
- contrib-contracts/modules/StarcoinVerifier.move
- contrib-contracts/src/eth_state_verifier_test/mod.rs
- contrib-contracts/src/genesis_nft_test.rs
- contrib-contracts/src/merkle_distributor_test.rs
- contrib-contracts/src/starcoin_merkle_test.rs
- scripts/nextest.sh
- test-helper/src/executor.rs
- vm/compiler/Cargo.toml
- vm/compiler/src/lib.rs
- vm/framework/move-stdlib/Cargo.toml
- vm/framework/move-stdlib/src/lib.rs
- vm/stdlib/src/lib.rs
- vm/types/src/contract_event.rs
- vm/types/src/on_chain_resource/block_metadata.rs
- vm/types/src/state_view.rs
> [compiler-v2]fix crate contrib contracts test(ignore test_merkle_distributor)

- chain/tests/test_force_upgrade.rs
> fix test_force_upgrade_1

- chain/src/chain.rs
- executor/src/block_executor.rs
- executor/src/lib.rs
- genesis/src/lib.rs
- vm/starcoin-transactional-test-harness/src/lib.rs
- vm/vm-runtime/tests/test_native_functions.rs
> Refactor genesis transaction

- cmd/starcoin/src/chain/get_block_info_cmd.rs
- cmd/starcoin/src/chain/get_ghost_dag_data.rs
- cmd/starcoin/src/chain/mod.rs
- rpc/api/generated_rpc_schema/chain.json
- rpc/api/src/chain/mod.rs
- rpc/client/src/lib.rs
- rpc/server/src/module/chain_rpc.rs
- sync/src/tasks/block_sync_task.rs
- vm/starcoin-transactional-test-harness/src/fork_chain.rs
> Cmd sync optimization
