executor/src/executor_test.rs
executor/src/mock_executor.rs
txpool/src/pool_client.rs
vm/vm-runtime/src/mock_vm.rs

add simple txn verification.
currently, only check signature and compare seq number.

txn verify in vm

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/tests/test_block_chain.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
core/traits/src/lib.rs
miner/src/lib.rs
miner/src/miner.rs
miner/src/tests/mod.rs
sync/src/download.rs
sync/src/process.rs
sync/src/tests/sync_actor_test.rs

1.  refactor ChainAsyncService;
2. remove AsyncChain;

[traits]refactor ChainAsyncService.

---

chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
core/traits/src/chain_service.rs

1.  remove ChainReader from ChainServiceImpl;
2. refactor ChainService;

[traits]refactor chain_service.

---

chain/src/chain_service.rs
core/traits/src/chain_service.rs

[chain]change head branch to master.

---

config/src/txpool_config.rs

[config]: ignore txn for now

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/tests/test_block_chain.rs
core/genesis/src/lib.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
miner/src/lib.rs
miner/src/tests/mod.rs
storage/src/lib.rs
sync/src/download.rs
sync/src/process.rs
sync/src/tests/sync_actor_test.rs
types/src/startup_info.rs

[chain]refactor BlockChain

---

chain/src/chain_service.rs
chain/src/lib.rs

add bus for chain_service to broadcast NewHeadBlock.

[chain]add bus for chain_service to broadcast NewHeadBlock.

---

chain/src/chain_service.rs
chain/src/lib.rs
miner/src/lib.rs

[chain]refactor chain_service.

---

config/src/lib.rs
config/src/storage_config.rs
node/src/main.rs

[config]: fix storage config

---

Cargo.lock
executor/src/mock_executor.rs
miner/src/lib.rs
miner/src/mock_txn_generator.rs
miner/src/tx_factory.rs
txpool/src/pool_client.rs
txpool/src/tx_pool_service_impl.rs
vm/vm-runtime/src/mock_vm.rs

impl mock generator as a txn factory.

[miner]: add mock txn

---

Cargo.lock
network/src/lib.rs
network/src/net.rs
network/src/net_test.rs
network/src/network.rs
sync/src/download.rs
sync/src/download_body.rs
sync/src/download_header.rs
sync/src/process.rs
sync/src/sync.rs
sync/tests/sync_actor_test.rs
types/Cargo.toml
types/src/lib.rs
types/src/messages.rs
types/src/sync_messages.rs

refractor code

---

network/src/network.rs
types/src/peer_info.rs

add peer set

---

Cargo.lock
Cargo.toml
cmd/tx-factory/Cargo.toml
cmd/tx-factory/README.md
cmd/tx-factory/src/lib.rs
cmd/tx-factory/src/main.rs
cmd/tx-factory/src/txn_generator.rs

This doesn't remove the origin tx factory impl in miner crate.
Another PR is needed to remove it when appropriate.

[txfactory] add standalone txfactory binary

---

network/src/network.rs

add total difficulty in peer info

add total difficulty

---

chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
core/traits/src/chain_service.rs
network-p2p/api/src/messages.rs
network-p2p/api/src/sync_messages.rs
sync/src/download.rs
sync/src/download_body.rs
sync/src/download_header.rs
sync/src/process.rs

[sync]sync block_info

---

sync/src/download.rs
sync/src/state_sync/mod.rs

[state-sync]refactor StateSyncTaskActor.

---

config/src/network_config.rs
miner/tests/miner_test.rs
network/src/net.rs
network/src/net_test.rs
network/src/network.rs
node/src/node.rs
sync/tests/sync_actor_test.rs

add genesis hash from genesis block

add genesis hash from genesis block

---

consensus/src/argon_consensus.rs
consensus/src/dummy.rs
consensus/src/lib.rs

genesis header config by ChainConfig.

[consensus] remove init_genesis_header from Consensus Trait

---

commons/scmd/examples/hello_main.rs
commons/scmd/src/lib.rs

set display order to sub commands. https://github.com/starcoinorg/starcoin/issues/132

[scmd] fix help display subcommands bug

---

Cargo.lock
cmd/starcoin/src/account/mod.rs
cmd/starcoin/src/account/unlock_cmd.rs
cmd/starcoin/src/main.rs
config/src/account_vault_config.rs
config/src/lib.rs
rpc/api/src/account/mod.rs
rpc/client/src/lib.rs
rpc/server/src/module/account_rpc.rs
wallet/api/src/lib.rs
wallet/api/src/mock/mock_wallet_service.rs
wallet/lib/src/keystore_wallet.rs
wallet/service/Cargo.toml
wallet/service/src/actor.rs
wallet/service/src/message.rs

[wallet]: use file storage and add unlock cmd

---

sync/src/download.rs
sync/src/state_sync/mod.rs
types/src/system_events.rs

1. min peer when state sync;
2. add StateSyncDone event;

[state-sync]refactor state-sync.

---

Cargo.lock
network-p2p/Cargo.toml
network-p2p/api/Cargo.toml
network-p2p/peerset/Cargo.toml
network/Cargo.toml
types/Cargo.toml

change libp2p dependency

---

Cargo.lock
sync/Cargo.toml
sync/api/Cargo.toml
sync/api/src/lib.rs
sync/src/download.rs
sync/src/state_sync/mod.rs
sync/tests/sync_actor_test.rs

1. reset StateSyncTask;
2. verify StateNode;

State-sync

---

network/src/network.rs

add network startup check

---

miner/tests/miner_test.rs
network-p2p/api/src/messages.rs
network-p2p/src/protocol.rs
network-p2p/src/service.rs
network/src/net.rs
network/src/net_test.rs
network/src/network.rs
node/src/node.rs
sync/tests/sync_actor_test.rs
types/src/block.rs

add peerinfo

---

Cargo.lock
network-p2p/api/src/sync_messages.rs
network/src/network.rs
sync/Cargo.toml
sync/src/download.rs
sync/src/download_body.rs
sync/src/download_header.rs
sync/src/helper.rs
sync/src/lib.rs
sync/src/process.rs
sync/src/state_sync/mod.rs
sync/src/sync.rs
sync/tests/full_sync_test.rs
types/src/system_events.rs

[sync]change send_request to send_request_bytes

---

sync/src/download.rs
sync/src/state_sync/mod.rs

[sync]fix best peer.

---

network/src/network.rs
sync/src/download.rs

return default peer_info when find best peer.

[network]fix bug

---

cmd/tx-factory/README.md
cmd/tx-factory/src/main.rs
cmd/tx-factory/src/txn_generator.rs

use account in node to do transfer txn(to faucet address or specified address).

[feature]: new txfacory logic

---

network/src/network.rs
sync/src/download.rs

[network]fix best peer.

---

cmd/starcoin/src/account/create_cmd.rs
cmd/starcoin/src/account/list_cmd.rs
cmd/starcoin/src/account/show_cmd.rs
cmd/starcoin/src/account/sign_txn_cmd.rs
cmd/starcoin/src/debug/log_cmd.rs
cmd/starcoin/src/main.rs
cmd/starcoin/src/state.rs
cmd/starcoin/src/txn/transfer.rs
commons/logger/src/lib.rs
commons/scmd/examples/hello_main.rs
commons/scmd/src/lib.rs
node/src/actor.rs
node/src/lib.rs
node/src/node.rs
node/tests/test_node_run.rs
rpc/api/src/debug/mod.rs
rpc/api/src/lib.rs
rpc/client/src/lib.rs
rpc/server/src/actor.rs
rpc/server/src/module/debug_rpc.rs
rpc/server/src/module/mod.rs

support set log level runtime.

[feature] debug command

---

cmd/faucet/src/faucet.rs
cmd/faucet/src/main.rs
cmd/starcoin/src/dev/get_coin_cmd.rs
cmd/starcoin/src/dev/mod.rs
cmd/starcoin/src/main.rs
cmd/starcoin/src/txn/transfer.rs
cmd/starcoin/src/wallet/create_cmd.rs
cmd/starcoin/src/wallet/export_cmd.rs
cmd/starcoin/src/wallet/import_cmd.rs
cmd/starcoin/src/wallet/list_cmd.rs
cmd/starcoin/src/wallet/show_cmd.rs
cmd/starcoin/src/wallet/unlock_cmd.rs
cmd/tx-factory/src/main.rs
config/src/chain_config.rs
config/src/lib.rs
rpc/api/src/wallet/mod.rs
rpc/client/src/lib.rs
rpc/server/src/actor.rs
rpc/server/src/module/account_rpc.rs
rpc/server/src/module/mod.rs
rpc/server/src/module/wallet_rpc.rs

implements https://github.com/starcoinorg/starcoin/issues/145

[cmd] implement a dev/get_coin command for dev network.

---

Cargo.lock
chain/src/chain_service.rs
chain/src/tests/test_block_chain.rs
consensus/src/dummy.rs

fix https://github.com/starcoinorg/starcoin/issues/196

[fix]dev panic #196

---

commons/scmd/examples/hello_main.rs
commons/scmd/src/result.rs

[scmd]  Optimize single value table display.

---

config/src/lib.rs
config/src/network_config.rs
node/src/node.rs
rpc/server/src/module/node_rpc.rs

[config] rename seeds to seed, and only accept one seed option. fix #211

---

cmd/starcoin/src/wallet/export_cmd.rs
cmd/starcoin/src/wallet/import_cmd.rs
cmd/starcoin/src/wallet/show_cmd.rs
cmd/starcoin/src/wallet/unlock_cmd.rs
commons/scmd/src/result.rs

[cmd] wallet cmd set default args

---

network/api/src/lib.rs

add dummy async service

---

Cargo.lock
cmd/starcoin/Cargo.toml
cmd/starcoin/src/crash_handler.rs
cmd/starcoin/src/debug/log_cmd.rs
cmd/starcoin/src/debug/mod.rs
cmd/starcoin/src/debug/panic_cmd.rs
cmd/starcoin/src/main.rs
node/src/lib.rs
node/tests/test_node_run.rs
rpc/api/src/debug/mod.rs
rpc/client/src/lib.rs
rpc/server/src/actor.rs
rpc/server/src/module/debug_rpc.rs

[feature]crash handler

---

config/src/lib.rs
config/src/sync_config.rs

[cli]add sync_mode command.

---

chain/src/chain_service.rs

save startup info when fast sync mode.

[chain]save startup info

---

network-p2p/src/behaviour.rs
network-p2p/src/debug_info.rs
network-p2p/src/discovery.rs
network-p2p/src/protocol.rs
network-p2p/src/protocol/generic_proto/behaviour.rs
network-p2p/src/service.rs
network/src/helper.rs
network/src/lib.rs
network/src/message_processor.rs
network/src/net.rs
network/src/network.rs

fix problem

---

.github/workflows/build_test.yml
.github/workflows/cancel.yml
.github/workflows/codecov.yml
scripts/coverage_report.sh

[ci] Generate code coverage report.

---

core/forkable-jellyfish-merkle/src/lib.rs
network-p2p/src/protocol/generic_proto/tests.rs
state/state-tree/src/state_tree_test.rs

[tree]: fix bug when inserting same kv value

---

examples/my_token/module/my_token.move
examples/my_token/readme.md
examples/my_token/scripts/adopt.move
examples/my_token/scripts/issue.move
examples/my_token/scripts/transfer.move

[vm] example to use token

---

Cargo.lock
deploy/prometheus.yml

add prometheus config file

---

Cargo.lock
Cargo.toml
commons/metrics/src/lib.rs
rpc/client/tests/client_server_test.rs
rpc/middleware/Cargo.toml
rpc/middleware/src/lib.rs
rpc/middleware/src/metrics.rs
rpc/server/Cargo.toml
rpc/server/src/actor.rs
rpc/server/src/service.rs

Add metrics middleware for rpc server
resolve #352

[devops] rpc metrics

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/mock/mock_chain_service.rs
cmd/starcoin/src/chain/branchs_cmd.rs
cmd/starcoin/src/chain/list_block_cmd.rs
cmd/starcoin/src/chain/mod.rs
cmd/starcoin/src/main.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
miner/src/lib.rs
rpc/api/src/chain/mod.rs
rpc/client/src/lib.rs
rpc/server/src/module/chain_rpc.rs
types/src/startup_info.rs

[cli] Improvement chain cmd

---

Cargo.lock
commons/metrics/src/lib.rs
commons/metrics/src/macros.rs
storage/Cargo.toml
storage/src/cache_storage/mod.rs
storage/src/db_storage/mod.rs
storage/src/lib.rs
storage/src/metrics.rs

[storage] Add storage metrics

---

Cargo.lock
chain/Cargo.toml
chain/src/chain_metrics.rs
chain/src/chain_service.rs
chain/src/lib.rs
commons/metrics/src/lib.rs
sync/Cargo.toml
types/src/startup_info.rs

[chain]Chain metrics

---

Cargo.lock
sync/Cargo.toml
sync/src/download.rs
sync/src/lib.rs
sync/src/state_sync/mod.rs
sync/src/sync_metrics.rs

[sync]add SyncMetrics.

---

Cargo.lock
bus/Cargo.toml
bus/src/bus.rs
bus/src/lib.rs
miner/src/ondemand_pacemaker.rs

[bus] Fix bus clear subscription bug.

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/mock/mock_chain_service.rs
rpc/server/src/actor.rs
sync/api/src/lib.rs
sync/api/src/sync_messages.rs
sync/src/download.rs
sync/src/sync.rs
types/src/startup_info.rs

[chain]Chain clippy

---

sync/src/download.rs
sync/src/download_body.rs
sync/src/download_header.rs
sync/src/pool/mod.rs
sync/src/process.rs
sync/src/state_sync/mod.rs
sync/src/sync.rs
sync/tests/state_sync_test.rs

[sync]Sync clippy

---

Cargo.lock
commons/metrics/Cargo.toml
commons/metrics/src/lib.rs
commons/metrics/src/metric_server.rs
commons/metrics/src/process_collector.rs

current only support macos and linux.

[metric]: use psutil to collect process info

---

sync/src/download.rs

[sync]State sync loop

---

chain/src/lib.rs
chain/src/message/mod.rs

[chain]Chain panic

---

chain/src/chain_service.rs

[chain]save branch

---

chain/src/chain.rs
config/src/chain_config.rs
consensus/src/argon.rs
consensus/src/difficulty.rs
consensus/src/lib.rs
core/genesis/src/lib.rs
core/traits/src/consensus.rs
miner/src/miner.rs
miner/src/miner_client/test.rs
miner/src/miner_client/worker.rs
miner/src/stratum.rs
network/src/network.rs
node/src/node.rs
types/src/block.rs
types/src/peer_info.rs

The script is
find . -path './target' -prune -o -name "*.rs"|
grep -v target|xargs sed -i 's/difficult\>/difficulty/g'

refactor: Change all "difficult" to "difficulty"

---

chain/src/chain.rs
node/src/node.rs
sync/src/download.rs
sync/src/process.rs

[chain]Used time

---

network/src/network.rs

remove unwrap

---

Cargo.lock
benchmarks/Cargo.toml
benchmarks/benches/bench_chain.rs
benchmarks/src/chain.rs
benchmarks/src/lib.rs

[bench]Chain bench

---

benchmarks/benches/bench_chain.rs
benchmarks/src/chain.rs

[bench]add query_master_block.

---

Cargo.lock
config/src/rpc_config.rs
rpc/server/Cargo.toml
rpc/server/src/module/pubsub.rs
rpc/server/src/module/pubsub/tests.rs
rpc/server/src/service.rs
txpool/Cargo.toml
txpool/src/lib.rs
txpool/src/test.rs
txpool/src/test_helper.rs

[pubsub]: add unit test on pubsub

---

sync/api/src/lib.rs
sync/src/download.rs
sync/src/state_sync/mod.rs
sync/src/sync_metrics.rs

1. add ACT;
2. retry when sync failed.

[state_sync]retry when sync failed.

---

chain/src/chain_service.rs

broadcast Head event when rollback

[chain]broadcast Head event when rollback

---

Cargo.lock
cmd/starcoin/Cargo.toml
cmd/starcoin/src/dev/mod.rs
cmd/starcoin/src/dev/subscribe_cmd.rs
cmd/starcoin/src/main.rs
config/src/lib.rs
rpc/api/Cargo.toml
rpc/api/src/types/event.rs
rpc/api/src/types/pubsub.rs
rpc/client/src/lib.rs
rpc/client/src/pubsub_client.rs
rpc/client/tests/client_server_test.rs
rpc/server/src/module/pubsub.rs

This PR:
- implement a pubsub client for starcoin subscription.
- add `dev subscribe` related sub commands.
- client connects to node by websocket instead of http.

feat(pubsub): make pubsub available from cli

---

benchmarks/src/sync.rs
sync/src/download.rs
sync/src/download_body.rs

[sync]await to connect block.

---

core/genesis/src/lib.rs
executor/src/block_executor.rs
executor/src/executor.rs
executor/src/executor_test.rs
executor/src/lib.rs
types/src/error/mod.rs
vm/vm-runtime/src/starcoin_vm.rs

Batch transactions instead of processing each transaction
independently to make effective use of module caching

[vm] optimize transaction execution time

---

chain/src/chain.rs
chain/src/chain_service.rs
storage/src/tests/test_block.rs
sync/api/src/lib.rs
sync/src/download.rs
sync/src/state_sync/mod.rs
types/src/block.rs

add parent_block_accumulator_root into BlockHeader.

[fast_sync]add parent_block_accumulator_root into BlockHeader.

---

chain/src/chain_service.rs
chain/src/lib.rs
miner/src/headblock_pacemaker.rs
miner/src/miner.rs
miner/src/ondemand_pacemaker.rs
network/api/src/lib.rs
network/src/network.rs
node/src/node.rs
rpc/server/src/module/pubsub/event_subscription_actor.rs
rpc/server/src/module/pubsub/tests.rs
state/service/src/actor.rs
sync/api/src/lib.rs
sync/src/download.rs
sync/tests/full_sync_test.rs
sync/tests/state_sync_test.rs
txpool/src/tx_pool_service_impl.rs
types/src/system_events.rs

[type]: refactor system event into standalone events

---

config/src/chain_config.rs
config/src/lib.rs
config/src/network_config.rs
network-p2p/src/config.rs
network/src/network.rs

add seed in chain config and config opt for disable seed

add seed in chain config and config opt for disable seed

---

chain/src/chain_service.rs
sync/api/src/lib.rs
sync/src/download.rs
sync/src/state_sync/mod.rs
types/src/block.rs

connected pivot block when state sync finish.

[state_sync]connected pivot block

---

config/src/sync_config.rs
sync/src/download.rs

[state_sync]sync_mode

---

sync/src/download.rs
sync/src/state_sync/mod.rs

return error during state sync.

[state_sync]state sync err

---

chain/src/chain.rs
config/src/miner_config.rs
executor/benchmark/src/lib.rs
executor/src/block_executor.rs
executor/src/executor_test.rs
rpc/server/src/module/pubsub/tests.rs

- Impose block_gas_limit when creating block templates.
- Also check gas related fields when apply block.
- Add test on block_execute to verify the gas_limit logic is correctly impled.

feature: block gas limit

---

benchmarks/src/sync.rs
chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/mock/mock_chain_service.rs
core/genesis/src/lib.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
storage/src/block/mod.rs
storage/src/lib.rs
storage/src/tests/test_block.rs
sync/src/download.rs
types/src/block.rs

support change sync mode after restart.

[sync]Feature/change sync mode

---

network-p2p/src/protocol.rs
network-p2p/src/service.rs
network/src/message_processor.rs
network/src/net.rs
network/src/network.rs

change log level,format and remove some comments

change log level and remove comments

---

chain/src/chain.rs
chain/src/chain_service.rs
sync/api/src/lib.rs
sync/src/download.rs
sync/src/download_body.rs
sync/src/download_header.rs
sync/src/pool/mod.rs
sync/src/process.rs
sync/src/state_sync/mod.rs
sync/src/sync.rs

[chain & sync]clear log.

---

benchmarks/src/sync.rs
chain/src/lib.rs
chain/src/mock/mock_chain_service.rs
chain/src/tests/test_block_chain.rs
core/traits/src/chain_service.rs
miner/tests/miner_test.rs
sync/src/download.rs
sync/src/pool/mod.rs
sync/src/process.rs
sync/src/state_sync/mod.rs
sync/tests/full_sync_test.rs
sync/tests/state_sync_test.rs

clear unwrap for chain and sync module.

[chain & sync]unwrap

---

config/src/sync_config.rs

default sync mode with dev net.

full sync mode

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/opened_block.rs
chain/src/test_helper.rs
chain/src/tests/mod.rs
chain/src/tests/test_block_chain.rs
chain/src/tests/test_opened_block.rs
core/traits/src/chain.rs
core/traits/src/lib.rs
miner/src/lib.rs
miner/src/stratum.rs
rpc/server/src/module/pubsub/tests.rs
types/src/block_metadata.rs
vm/vm-runtime/src/starcoin_vm.rs

This PR add a `OpenedBlock` abstraction which used to create block template.
Also close #527 and #561

[bugfix]: fix some bugs related to creating templates

---

txpool/src/pool/listener.rs
txpool/src/pool_client.rs
txpool/src/tx_pool_service_impl.rs

txpool has a few changes.
state is ok for me.

recheck log in txpool&state

---

chain/src/chain_service.rs
config/src/network_config.rs
network-p2p/src/config.rs
network-p2p/src/lib.rs
network-p2p/src/service.rs
network-p2p/src/service_test.rs
network/api/src/lib.rs
network/api/src/messages.rs
network/src/net.rs
network/src/net_test.rs
network/src/network.rs
sync/src/get_txns_handler.rs
sync/src/helper.rs
txpool/tx-relay/src/lib.rs
types/src/lib.rs

add multi protocol support for send message

add protocol name support

---

Cargo.lock
bus/src/lib.rs
chain/Cargo.toml
commons/stest/Cargo.toml
commons/stest/src/lib.rs
commons/stest/stest-macro/src/lib.rs
rpc/server/Cargo.toml
state/service/Cargo.toml
wallet/service/Cargo.toml

add assert fail support in stest macro

add assert fail support in stest macro

---

storage/src/accumulator/mod.rs
storage/src/block/mod.rs
storage/src/cache_storage/mod.rs
storage/src/lib.rs
storage/src/storage.rs
storage/src/storage_macros.rs

1. Fix unnessary unwrap
2. Remove allow dead code
3. Update cache and db concurrent issue

review: Fix some issue found in storage

---

commons/stest/src/lib.rs
commons/stest/stest-macro/src/lib.rs

change tokio to stest

---

benchmarks/src/sync.rs
chain/src/message/mod.rs
miner/tests/miner_test.rs
network-p2p/src/protocol.rs
network-p2p/src/protocol/generic_proto/behaviour.rs
network-p2p/src/service.rs
network/api/src/lib.rs
network/api/src/messages.rs
network/src/net.rs
network/src/network.rs
node/src/node.rs
sync/src/helper.rs
sync/tests/gen_network/mod.rs
types/src/peer_info.rs
types/src/startup_info.rs

[network & sync]upgrade sync protocol

---

commons/logger/src/lib.rs

Now, we can set debug level directly for a specified module or crate.
```
RUST_LOG=info,starcoin_network=debug
RUST_LOG=warn,starcoin_vm=debug,starcoin_network=info
```

[logger]: support RUST_LOG style like env_logger

---

Cargo.lock
benchmarks/Cargo.toml
benchmarks/benches/bench_chain.rs
benchmarks/benches/bench_state_tree.rs
benchmarks/benches/bench_sync.rs
benchmarks/benches/bench_vm.rs
benchmarks/benches/benchmarks.rs
benchmarks/src/sync.rs

add bench log.

---

scripts/starcoin_ci_docker.sh

打印日志时 peerid 的标志变了。这里的 grep 也更新下。

ci:scripts: Update the grep cmd for finding self peerid

---

network-p2p/src/service_test.rs

remove ignored test

---

Cargo.lock
cmd/starcoin/src/cli_state.rs
cmd/starcoin/src/main.rs
commons/scmd/Cargo.toml
commons/scmd/examples/hello_main.rs
commons/scmd/src/context.rs
config/src/lib.rs

[scmd] Console support persistence history to file

---

network-p2p/src/protocol.rs
network-p2p/src/protocol/generic_proto/behaviour.rs
network-p2p/src/protocol/generic_proto/handler/group.rs
network-p2p/src/protocol/generic_proto/tests.rs
network-p2p/src/protocol/message.rs
network/src/network.rs

remove send packet function

---

commons/logger/src/lib.rs
network-p2p/src/protocol.rs
network-p2p/src/protocol/generic_proto/behaviour.rs
network-p2p/src/protocol/generic_proto/handler/group.rs
network-p2p/src/protocol/message.rs

add fallback message

---

config/src/network_config.rs
network-p2p/src/protocol.rs
network-p2p/src/service_test.rs
network/src/network.rs

remove duplicate protocol name

remove duplicate protocol name

---

network/src/network.rs

fix test problem

---

sync/src/download.rs

[sync]update sync_block_from_best_peer.

---

vm/functional-tests/src/account.rs

AccountData in functional-tests fall behind with Account Struct in Move contract.
It causes withdraw failure in tests.
This PR fixes it.

[vm]: fix functional-tests account data

---

network-p2p/src/lib.rs
network-p2p/src/service.rs
network/src/lib.rs
network/src/net.rs
network/src/network.rs

1. remove unused Ack message.
2. fix boot_node_ids empty bug.
resolve #653

[network] Clean network code.

---

node/src/node.rs

resolve #553
一定程度能解决遗留 ipc 文件的问题。

[node] Start rpc service last at node start, avoid remain ipc file when sync interrupt

---

chain/open-block/src/lib.rs
chain/src/chain.rs
executor/benchmark/src/lib.rs
executor/src/block_executor.rs
executor/src/executor_test.rs
txpool/src/test.rs

[block]: execute block meta in the first place

---

Cargo.lock
executor/src/executor_test.rs
vm/compiler/Cargo.toml
vm/compiler/src/contract/mod.rs
vm/compiler/src/lib.rs
vm/types/Cargo.toml
vm/types/src/lib.rs

Module 兼容性检查，需要补充更多的测试用例，以及和 UpgradePackage transaction 整合。

[compiler] Implement module compat check, define module,struct,function `Contract`

---

benchmarks/src/chain.rs
benchmarks/src/sync.rs
chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/mock/mock_chain_service.rs
core/genesis/src/lib.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
core/traits/src/lib.rs
sync/api/src/lib.rs
sync/src/block_connector/mod.rs
sync/src/block_sync/mod.rs
sync/src/download.rs
sync/src/helper.rs
sync/src/lib.rs
sync/src/process.rs
sync/src/state_sync/mod.rs
sync/src/sync_metrics.rs

[chain & sync]verify block

---

benchmarks/src/sync.rs
config/src/available_port.rs
config/src/lib.rs
config/src/metrics_config.rs
config/src/miner_config.rs
config/src/network_config.rs
config/src/rpc_config.rs
network-p2p/src/service_test.rs
network/src/net_test.rs
network/src/network.rs
sync/tests/full_sync_test.rs
sync/tests/state_sync_test.rs
sync/tests/txn_sync_test.rs

This will make `get_available_port` more stable.

config: make get_available_port stable

---

vm/compiler/src/lib.rs

[compiler] Fix compiler pre process source place holder replace panic bug

---

cmd/miner_client/src/lib.rs
cmd/miner_client/src/worker.rs
consensus/src/argon.rs
consensus/src/lib.rs
consensus/tests/consensus_test.rs
miner/src/miner.rs
types/src/block.rs

[consensus]add verify_header_test.

---

Cargo.lock
Cargo.toml
vm/functional-tests/tests/testsuite/authenticator/authenticator.move
vm/functional-tests/tests/testsuite/debug/debug.move
vm/functional-tests/tests/testsuite/natives/hash_model.move
vm/functional-tests/tests/testsuite/natives/lcs.move
vm/functional-tests/tests/testsuite/natives/signature.move
vm/functional-tests/tests/testsuite/shared_ed25519_public_key/shared_key.move
vm/move-coverage/Cargo.toml
vm/move-coverage/baseline/coverage_report
vm/move-coverage/check_coverage.bash
vm/move-coverage/gather_stats.bash
vm/move-coverage/src/bin/coverage-summaries.rs
vm/move-coverage/src/bin/move-trace-conversion.rs
vm/move-coverage/src/bin/source-coverage.rs
vm/move-coverage/src/coverage_map.rs
vm/move-coverage/src/lib.rs
vm/move-coverage/src/source_coverage.rs
vm/move-coverage/src/summary.rs
vm/move-coverage/update_baseline.bash
vm/types/Cargo.toml
vm/types/src/lib.rs

vm/move-coverage目录下：
check_coverage.bash 检查覆盖率
gather_stats.bash 统计覆盖率

[vm] add move coverage stat

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
chain/src/message/mod.rs
chain/src/mock/mock_chain_service.rs
cmd/starcoin/src/debug/gen_dev_uncle_cmd.rs
cmd/starcoin/src/debug/get_block_by_uncle.rs
cmd/starcoin/src/debug/mod.rs
cmd/starcoin/src/lib.rs
config/src/miner_config.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
rpc/api/src/chain/mod.rs
rpc/client/src/lib.rs
rpc/server/Cargo.toml
rpc/server/src/module/chain_rpc.rs

[cmd]uncle cmd

---

cmd/miner_client/src/stratum.rs
consensus/src/argon.rs

* Fix unwrap in miner client
* Make header hex & decode in transport layout

consensus: Fix some issue

---

cmd/starcoin/src/dev/deploy_cmd.rs
cmd/starcoin/src/dev/execute_cmd.rs
cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
cmd/starcoin/src/dev/upgrade_stdlib_cmd.rs
cmd/starcoin/src/wallet/execute_builtin_script_cmd.rs
core/genesis/src/lib.rs
txpool/src/pool/listener.rs
vm/functional-tests/src/account.rs
vm/functional-tests/src/config/transaction.rs
vm/functional-tests/src/evaluator.rs
vm/stdlib/modules/TransactionTimeout.move
vm/transaction-builder/src/lib.rs
vm/types/src/transaction/helpers.rs
vm/types/src/transaction/mod.rs
vm/types/src/transaction_metadata.rs
vm/vm-runtime/src/starcoin_vm.rs

解决 #879 中的 1，3 问题。
txpool 的改动，我另外再开一个PR搞。

feat: update txn expiration time from duration to unix timestamp

---

Cargo.lock
chain/src/chain.rs
chain/src/chain_service.rs
consensus/src/argon.rs
sync/src/download.rs

* Fix sync do not exist when it's block number lager than best peer
* Skip consensus verify in uncle block

Fix some issue

---

sync/src/block_sync/mod.rs
sync/src/download.rs

sync: Fix sync_block_from_best_peer_inner assert failed panic

---

Cargo.lock
sync/src/block_connector/mod.rs
sync/src/download.rs

[sync]future block pool

---

cmd/starcoin/src/debug/gen_dev_block_cmd.rs
cmd/starcoin/src/debug/mod.rs
cmd/starcoin/src/lib.rs
rpc/api/src/chain/mod.rs
rpc/client/src/lib.rs
rpc/server/src/module/chain_rpc.rs

[cmd]gen_dev_block

---

chain/src/chain_service.rs

fix create_block_template bug.

[chain]create_block_template

---

benchmarks/src/sync.rs
network-rpc/api/src/lib.rs
network-rpc/src/rpc.rs
sync/src/block_sync/mod.rs
sync/src/helper.rs

add get_header_by_hash rpc proto.

[sync]get_header_by_hash

---

benchmarks/src/sync.rs
network-rpc/api/src/lib.rs
network-rpc/src/rpc.rs
sync/src/block_sync/mod.rs
sync/src/download.rs
sync/src/helper.rs

[sync]verify

---

network-rpc/api/src/lib.rs
network-rpc/src/rpc.rs
sync/src/helper.rs

[sync]option

---

chain/src/chain.rs
chain/src/chain_service.rs
chain/src/lib.rs
core/traits/src/chain.rs
core/traits/src/chain_service.rs
network-rpc/api/Cargo.toml

Reverts starcoinorg/starcoin#1025

Revert "chain: Clean codes"

---

cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs

resolve https://github.com/starcoinorg/starcoin/issues/1004

fix: txn arg parsing

---

config/src/txpool_config.rs
txpool/src/pool.rs
txpool/src/pool/queue.rs
txpool/src/pool/verifier.rs
txpool/src/tx_pool_service_impl.rs

[txpool] Clean txpool config.

---

account/lib/src/account_manager.rs
account/lib/src/account_test.rs

fix: import account not show in cli

---

sync/src/helper.rs

pivot is none

---

Cargo.lock
benchmarks/src/chain.rs
benchmarks/src/sync.rs
chain/src/test_helper.rs
chain/src/tests/test_block_chain.rs
cmd/starcoin/Cargo.toml
cmd/starcoin/src/main.rs
commons/scmd/examples/hello_main.rs
commons/scmd/src/context.rs
core/genesis/Cargo.toml
core/genesis/src/errors.rs
core/genesis/src/lib.rs
miner/tests/miner_test.rs
network-rpc/src/tests.rs
node/Cargo.toml
node/src/lib.rs
node/src/node.rs
node/tests/test_node_run.rs
rpc/server/src/module/test_helper.rs
storage/src/db_storage/mod.rs
sync/tests/full_sync_test.rs
sync/tests/state_sync_test.rs
sync/tests/txn_sync_test.rs
testsuite/features/cmd.feature
testsuite/features/integration.feature
testsuite/tests/steps/node.rs
txpool/src/test_helper.rs

1. Do not exist process in run_node, do it in cli main.
2. Refactor genesis, provider init_storage by genesis.

[node] Refactor node start.

---

benchmarks/src/chain.rs
benchmarks/src/sync.rs
chain/src/chain.rs
chain/src/chain_service.rs
chain/src/test_helper.rs
chain/src/tests/test_block_chain.rs
config/src/miner_config.rs
core/genesis/src/lib.rs
core/traits/src/chain.rs
executor/src/executor_test.rs
miner/src/lib.rs
rpc/server/src/module/pubsub/tests.rs
rpc/server/src/module/test_helper.rs
types/src/block.rs
vm/vm-runtime/src/starcoin_vm.rs

1. Remove NodeConfig from BlockChain.
2. Use on chain config block gas limit.

[chain] Refactor block chain and block gas limit.

---

Cargo.lock
cmd/miner_client/Cargo.toml
cmd/miner_client/src/miner.rs
cmd/miner_client/src/stratum.rs
cmd/miner_client/src/test.rs
cmd/miner_client/src/worker.rs
miner/src/headblock_pacemaker.rs
miner/src/lib.rs
miner/src/miner.rs
miner/src/ondemand_pacemaker.rs
miner/src/stratum.rs
miner/stratum/Cargo.toml
miner/stratum/src/lib.rs
miner/stratum/src/traits.rs
types/src/block.rs

1. Fix ALLOWED_FUTURE_BLOCKTIME check bug.
2. Reactive miner by a GenerateBlockEvent after mint block fail.

[miner] Fix future time check bug and refactor miner.

---

sync/src/download.rs
sync/src/helper.rs
sync/src/state_sync/mod.rs
types/src/peer_info.rs

[sync]sync pivot block info

---

cmd/starcoin/src/state/get_cmd.rs
vm/resource-viewer/src/lib.rs

output move resource as a real struct data instead of string.

impl serialize for annotated resource

---

benchmarks/src/sync.rs
sync/src/download.rs

[sync]total_difficulty

---

vm/transaction-builder-generator/examples/cpp/stdlib_demo.cpp
vm/transaction-builder-generator/examples/java/StdlibDemo.java
vm/transaction-builder-generator/examples/python3/stdlib_demo.py
vm/transaction-builder-generator/src/cpp.rs
vm/transaction-builder-generator/src/generate.rs
vm/transaction-builder-generator/src/java.rs
vm/transaction-builder-generator/src/python3.rs
vm/transaction-builder-generator/tests/generation.rs

fix python java cpp generator

---

chain/src/chain.rs
chain/src/chain_service.rs
core/traits/src/lib.rs
executor/src/lib.rs
sync/src/block_connector/mod.rs

清理了一下 apply & apply_without_execute 的重复代码。

[chain] Refactor chain for eliminate repeat code

---

network/src/message_processor.rs
network/src/network.rs
node/src/node.rs
sync/src/download.rs

1. Send BeginSync Event;
2. Min block number;
3. Add network log;

[sync & node & network]BeginSync

---

vm/stdlib/modules/Token.move

add ensures to Token

---

miner/tests/miner_test.rs
network/api/src/messages.rs
network/src/lib.rs
network/src/network.rs
node/src/node.rs

txn&block broadcaster depends on network service.

refactor(network): seperate txn and block broadcast from network service

---

Cargo.lock
vm/transaction-builder-generator/Cargo.toml
vm/transaction-builder-generator/src/dart.rs
vm/transaction-builder-generator/src/generate.rs
vm/transaction-builder-generator/src/lib.rs
vm/transaction-builder-generator/src/rust.rs
vm/transaction-builder-generator/tests/generation.rs

change depts

---

chain/mock/src/lib.rs
chain/mock/src/mock_chain.rs
chain/src/chain.rs
chain/src/tests/test_blockchain.rs

test uncle block

---

Cargo.lock
commons/scmd/Cargo.toml
commons/scmd/src/context.rs

[scmd] Fix build error at out of git directory.

---

miner/src/create_block_template/mod.rs
miner/src/create_block_template/test_create_block_template.rs

add test_create_block_template.

[miner]test_create_block_template.

---

network-rpc/api/src/lib.rs
network-rpc/core/src/lib.rs
sync/src/block_sync/mod.rs
sync/src/block_sync/test_block_sync.rs
test-helper/src/chain.rs
test-helper/src/dummy_network_service.rs

Test block sync

---

sync/src/state_sync/mod.rs
sync/src/state_sync/test_state_sync.rs

[state sync]StateSyncTaskEvent

---

chain/src/chain.rs
miner/src/create_block_template/test_create_block_template.rs

[chain]uncle block.

---

network/src/network.rs
sync/tests/test_sync/mod.rs

compare total difficulty when broadcast.

[network]optimize broadcast.

---

miner/src/create_block_template/mod.rs
sync/src/block_connector/write_block_chain.rs
types/src/startup_info.rs
types/src/system_events.rs

1. map be uncles;
2. prune uncles;

[miner]Uncle

---

sync/tests/full_sync_test.rs

add test_broadcast_with_difficulty.

[sync]test_broadcast_with_difficulty

---

Cargo.lock
commons/service-registry/tests/common/cal_service.rs
commons/service-registry/tests/common/loop_task_service.rs
commons/service-registry/tests/common/mod.rs
commons/service-registry/tests/loop_task.rs
network-rpc/api/src/lib.rs
network-rpc/src/tests.rs
network/api/Cargo.toml
network/api/src/lib.rs
network/api/src/peer_provider.rs
network/src/network.rs
network/tests/network_rpc_test.rs
rpc/server/src/module/node_rpc.rs
sync/src/download.rs
sync/src/helper.rs
sync/src/txn_sync/mod.rs
sync/tests/full_sync_test.rs
test-helper/src/dummy_network_service.rs
types/src/peer_info.rs

1. [network] Refactor NetworkService trait, extract a PeerProvider trait  for handle peer selector strategy.
2. [service-registry] Add a loop task test for ActorService test.

[network] Refactor NetworkService trait, extract a PeerProvider trait  for handle peer selector strategy.

---

network/src/helper.rs
network/src/message_processor.rs

[network]test

---

Cargo.lock
chain/src/chain.rs
network/src/net.rs
sync/Cargo.toml
sync/src/block_connector/mod.rs
sync/src/block_connector/test_illegal_block.rs
sync/src/block_connector/test_write_block_chain.rs
vm/types/src/on_chain_config/consensus_config.rs

Test illegal block

---

chain/src/chain.rs
chain/src/tests/mod.rs
chain/src/tests/test_block_chain.rs

[chain]test test_apply_without_exe

---

chain/src/chain.rs

1、fix verify uncle bug;
2、verify repeat uncle in current block;
3、change to verify_block;

[chain]verify uncle.

---

sync/src/block_connector/test_illegal_block.rs

1. 叔块的父亲正好是上一个epoch的最后一个块【正常情况】；
2. 同一个block中存在重复叔块【非正常情况】；
3. 叔块的number不等于其父区块的number+1【非正常情况】；

[sync]test uncle block.

---

chain/src/chain.rs
chain/src/tests/test_block_chain.rs

fix: fix event filter overflow when from_block is 0

---

cmd/starcoin/src/dev/execute_cmd.rs
cmd/starcoin/src/view.rs
commons/scmd/src/context.rs
commons/scmd/src/result.rs
vm/types/src/account_config/events/dao.rs
vm/types/src/account_config/events/mod.rs

- support json output in console.
- update event view.
- merge exec of builtin script with `dev execute` to utilize dry-run.

some ue update

---

core/accumulator/src/accumulator_test.rs
core/accumulator/src/lib.rs
core/accumulator/src/tree.rs

1. Add a batch method for get leaves.
2. Fix get nodes return None instead of ACCUMULATOR_PLACEHOLDER_HASH.
3. remove Mutex from AccumulatorTree

[accumulator] Enhancement and optimize accumulator

---

vm/stdlib/modules/Box.move
vm/stdlib/modules/Offer.move
vm/stdlib/modules/Timestamp.move
vm/stdlib/modules/TokenLockPool.move
vm/stdlib/modules/doc/Box.md
vm/stdlib/modules/doc/Offer.md
vm/stdlib/modules/doc/Timestamp.md
vm/stdlib/modules/doc/TokenLockPool.md

add spec for Box  & Offer & TokenLockPool.

[stdlib]spec for Box  & Offer & TokenLockPool.

---

cmd/starcoin/src/account/show_cmd.rs
cmd/starcoin/src/dev/derive_account_address_cmd.rs
cmd/starcoin/src/view.rs

doc update https://github.com/starcoinorg/website/pull/33

update on cli in order to make multisig txn doc work

---

Cargo.lock
cmd/miner_client/src/worker.rs
commons/logger/Cargo.toml
commons/logger/src/lib.rs
types/src/block.rs

[log] Set third party crate's default log level, for reduce debug log.

---

consensus/src/difficulty.rs

1. update window;
2. BlockHeader into BlockDiffInfo;

[consensus]window.

---

Cargo.lock
cmd/starcoin/src/dev/call_contract_cmd.rs
rpc/api/Cargo.toml
rpc/api/src/dev.rs
rpc/api/src/types.rs
rpc/api/src/types/contract_call.rs
rpc/client/src/lib.rs
rpc/server/src/module/dev_rpc.rs
rpc/server/src/service.rs
vm/dev/src/playground.rs
vm/resource-viewer/src/lib.rs

return json directly for contract call api.

api: unify contract call api

---

Cargo.lock
cmd/tx-factory/Cargo.toml
cmd/tx-factory/src/main.rs
cmd/tx-factory/src/txn_generator.rs
kube/manifest/starcoin.yaml
miner/src/create_block_template/mod.rs

- create a specified number of accounts and deposit enough STC (INITIAL_BALANCE)
- accounts transfer STC to each other, sleep 500ms if txn submitting limitation(16) is reached.

[stress test] add stress test tool based on txn factory

---

cmd/tx-factory/src/main.rs
cmd/tx-factory/src/txn_generator.rs
kube/manifest/starcoin.yaml

- refactor the method to fetch expiration time
- disable stress by default

[stress test] improve the method to set expiration time

---

cmd/starcoin/src/account/execute_builtin_script_cmd.rs
cmd/starcoin/src/dev/call_contract_cmd.rs
cmd/starcoin/src/dev/compile_cmd.rs
cmd/starcoin/src/dev/execute_cmd.rs
cmd/starcoin/src/dev/generate_multisig_txn_cmd.rs
cmd/starcoin/src/dev/subscribe_cmd.rs

fix console error sometimes

---

cmd/starcoin/src/dev/sign_txn_helper.rs
core/genesis/src/lib.rs
vm/types/src/account_config/resources/module_upgrade_strategy.rs

[test]test_only_new_module

---

vm/functional-tests/tests/testsuite/token/split_fixed_key.move
vm/functional-tests/tests/testsuite/token/split_linear_key.move

add split_fixed_key & split_linear_key;

[functional-tests]split_fixed_key & split_linear_key

---

cmd/starcoin/src/node/info_cmd.rs
cmd/starcoin/src/node/peers_cmd.rs
cmd/starcoin/src/view.rs
commons/scmd/src/context.rs
commons/scmd/src/result.rs
rpc/api/src/node/mod.rs
rpc/api/src/types.rs
rpc/client/src/lib.rs
rpc/client/tests/client_server_test.rs
rpc/server/src/module/node_rpc.rs
types/src/peer_info.rs

[scmd] Support set output format in console.
[rpc] Define PeerInfoView

Support set output format in console

---

Cargo.lock
storage/Cargo.toml

[storage] Clean some unused deps.

---

Cargo.lock
config/src/lib.rs
config/src/rpc_config.rs
rpc/middleware/Cargo.toml
rpc/middleware/src/lib.rs
rpc/middleware/src/rate_limit.rs
rpc/server/src/api_registry.rs
rpc/server/src/service.rs

实现了接口级别的 ratelimit。看了一圈， 确认 jsonrpc 中获取不到 http ip，用户级别的 rate limit 暂时没法搞。

rpc: rate limit api

---

miner/src/create_block_template/mod.rs
miner/src/create_block_template/test_create_block_template.rs
vm/types/src/time.rs

[miner] Adjust time by parent block's timestamp when create block template.

---

Cargo.lock
network/Cargo.toml
network/api/Cargo.toml
network/api/src/lib.rs
network/api/src/peer_score.rs
network/src/broadcast_score_metrics.rs
network/src/helper.rs
network/src/lib.rs
network/src/service.rs
sync/src/tasks/mod.rs
sync/src/tasks/sync_score_metrics.rs
sync/src/verified_rpc_client.rs

1. peer score;
2. peer sync metrics;
3. peer broadcast metrics;

[sync & network]peer score.

---

account/api/src/message.rs
account/api/src/service.rs
account/lib/src/account_manager.rs
account/lib/src/account_test.rs
account/service/src/service.rs
cmd/starcoin/src/account/change_password_cmd.rs
cmd/starcoin/src/account/mod.rs
cmd/starcoin/src/lib.rs
commons/crypto/Cargo.toml
rpc/api/src/account/mod.rs
rpc/client/src/lib.rs
rpc/server/src/module/account_rpc.rs

rpc: account change password api

---

block-relayer/src/block_relayer.rs
chain/src/chain.rs
network/api/src/messages.rs
network/api/src/peer_provider.rs
network/src/service.rs
network/tests/network_service_test.rs
node/src/network_service_factory.rs
rpc/api/src/types.rs
rpc/server/src/module/pubsub/tests.rs
sync/src/sync2.rs
test-helper/src/network.rs
types/src/block.rs
types/src/startup_info.rs

[chain & network] Keep BlockInfo in ChainStatus and switch in network handshake

---

Cargo.lock
benchmarks/src/chain.rs
chain/api/src/message.rs
chain/api/src/service.rs
chain/mock/src/mock_chain.rs
chain/service/src/chain_service.rs
chain/src/chain.rs
cmd/generator/src/gen_data.rs
cmd/generator/src/gen_genesis.rs
cmd/generator/src/lib.rs
cmd/replay/src/main.rs
core/genesis/src/lib.rs
miner/src/create_block_template/test_create_block_template.rs
miner/tests/miner_test.rs
node/src/network_service_factory.rs
node/src/node.rs
storage/src/block/mod.rs
storage/src/chain_info/mod.rs
storage/src/lib.rs
storage/src/tests/test_block.rs
sync/src/block_connector/test_write_block_chain.rs
sync/src/tasks/tests.rs
test-helper/src/chain.rs
test-helper/src/network.rs
test-helper/src/txpool.rs
types/Cargo.toml
types/src/block.rs
types/src/startup_info.rs

1. Save genesis hash in storage.
2. Provider get chain info API in storage.
3. Do some storage cleanup.

[storage] Storage support get chain info.

---

chain/api/src/chain.rs
chain/api/src/lib.rs
chain/src/chain.rs
chain/src/verifier/mod.rs

[chain]Uncle

---

config/src/lib.rs
config/src/txpool_config.rs
miner/src/generate_block_event_pacemaker.rs
network/src/service.rs
state/api/src/chain_state.rs
test-helper/src/txpool.rs
txpool/api/src/lib.rs
txpool/src/lib.rs
txpool/src/tx_pool_service_impl.rs

- propagate new txn to random peers.
- propagate txns every x seconds.

tx: optimize tx propagation

---

Cargo.lock
account/api/src/message.rs
account/api/src/service.rs
account/lib/src/account.rs
account/lib/src/account_manager.rs
account/service/src/service.rs
dataformat-generator/Cargo.toml
rpc/api/src/account/mod.rs
rpc/api/src/txpool/mod.rs
rpc/server/src/module/account_rpc.rs
rpc/server/src/module/txpool_rpc.rs

- txpool.gas_price
- acount.sign_message
just a sketch.
details remain unimplemented.

rpc: add two apis.

---

cmd/starcoin/src/chain/stat/epoch_info.rs
cmd/starcoin/src/chain/verify/block.rs
cmd/starcoin/src/chain/verify/epoch_info.rs
cmd/starcoin/src/lib.rs
kube/manifest/centauri.yaml
kube/manifest/starcoin-namespaces.yaml
scripts/chain_verify.sh
scripts/prometheus_conf/rule.yml

1、修复了difficulty time_target验证的bug
2、压测环境独立namespace
3、减少block验证的区块数

[cmd-verify] update verify handle

---

Cargo.lock
cmd/starcoin/src/contract.rs
cmd/starcoin/src/dev/call_contract_cmd.rs
cmd/starcoin/src/dev/sign_txn_helper.rs
cmd/starcoin/src/lib.rs
cmd/starcoin/src/state/get_cmd.rs
cmd/starcoin/src/state/list_resource_cmd.rs
cmd/starcoin/src/state/mod.rs
cmd/starcoin/src/view.rs
network-rpc/api/src/remote_chain_state.rs
node/src/rpc_service_factory.rs
rpc/api/src/contract_api.rs
rpc/api/src/dev.rs
rpc/api/src/state/mod.rs
rpc/api/src/types.rs
rpc/client/src/lib.rs
rpc/client/src/remote_state_reader.rs
rpc/server/Cargo.toml
rpc/server/src/module/contract_rpc.rs
rpc/server/src/module/dev_rpc.rs
rpc/server/src/module/state_rpc.rs
state/api/src/chain_state.rs
state/api/src/lib.rs
state/api/src/message.rs
state/api/src/mock/mock_chain_state_service.rs
state/service/src/service.rs
state/statedb/src/lib.rs

rpc: impl list-resource api

---

cmd/starcoin/src/dev/get_coin_cmd.rs
cmd/starcoin/src/state/get_proof_cmd.rs
cmd/starcoin/src/view.rs
rpc/api/src/state/mod.rs
rpc/api/src/types.rs
rpc/client/src/lib.rs
rpc/client/src/remote_state_reader.rs
rpc/server/src/module/state_rpc.rs
state/api/src/chain_state.rs
testsuite/features/cmd.feature
testsuite/tests/steps/state.rs
types/src/lib.rs

api break：主要break了 stateproof rpc 接口。接口应该还没有被外部使用，应该没啥影响。

cli: remove some views

---

txpool/src/lib.rs

fix empty txn broadcast

---

config/src/network_config.rs
config/src/tests.rs
network-rpc/src/tests.rs
network/src/worker.rs
network/tests/network_node_test.rs
network/tests/network_service_test.rs
sync/tests/full_sync_test.rs
sync/tests/test_sync/mod.rs
sync/tests/txn_sync_test.rs
test-helper/src/network.rs

1. fix disable_mdns opt not work.
2. fix seeds opt conflict between vec and subcommand.

[config] Fix cmd network config and option.

---

README.md
config/src/network_config.rs
config/src/rpc_config.rs
config/src/tests.rs
kube/manifest/starcoin-halley.yaml
network-p2p/src/service.rs
network/src/worker.rs

set allow_non_globals_in_dht by discover_local.

[network & config] Add discover-local option and remove disable-mdns option

---

chain/src/verifier/mod.rs
miner/src/create_block_template/mod.rs

[chain] Use on chain config max_uncles_per_block when verify block header.

---

docker/Dockerfile_for_runner
kube/manifest/actions-runner-controller.yaml
kube/manifest/runner.yaml
network-p2p/src/request_responses.rs
rpc/server/src/module/pubsub/tests.rs
scripts/auto_rerun_test.sh
sync/src/tasks/block_sync_task.rs
sync/src/tasks/inner_sync_task.rs
sync/src/tasks/tests.rs
vm/functional-tests/tests/testsuite/epoch/epoch_data.move
vm/types/src/unit_tests/access_path_test.rs
x.toml

1. 增加测试验证 rpc 超时以及 sync 的 start_number 边界问题。
2. 升级以及修复 ci

sync and ci

---

Cargo.lock
cmd/starcoin/Cargo.toml
commons/crypto/Cargo.toml
commons/proptest-helpers/Cargo.toml
config/Cargo.toml
core/forkable-jellyfish-merkle/Cargo.toml
devtools/x/Cargo.toml
vm/compiler/Cargo.toml
vm/functional-tests/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-prover/Cargo.toml
vm/move-prover/src/cli.rs
vm/move-prover/src/pipelines.rs
vm/move-prover/src/prelude.bpl
vm/move-prover/tests/sources/functional/emits.exp
vm/move-prover/tests/sources/functional/emits.move
vm/move-prover/tests/sources/functional/simple_vector_client.move
vm/move-prover/tests/testsuite.rs
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

- move lang bug fix in diem side
- update move prover

[vm] upgrade to vm_03_08

---

cmd/starcoin/src/dev/compile_cmd.rs
cmd/starcoin/src/dev/execute_cmd.rs
test-helper/src/executor.rs
vm/stdlib/src/lib.rs

Fix stdlib file

---

network/api/src/peer_provider.rs
network/api/src/tests.rs
sync/src/sync2.rs
sync/src/verified_rpc_client.rs
sync/tests/full_sync_test.rs

Random target

---

rpc/api/src/types.rs

resource viewer 朱老师已经搬过来了。
这里就只把 rpc api的 struct 改了下。

fix annotated struct

---

kube/manifest/explorer/explorer-api-deployment.yaml
kube/manifest/explorer/service-explorer-api.yaml

1. chang v0.4.4 image tag
2. replicas change to 3
3.  change port to 80

[ci] release explorer-api v0.4.4

---

kube/manifest/explorer/explorer-api-deployment.yaml

starcoin/starcoin-explorer-api:v0.4.4
instead of
wk3368/starcoin-explorer-api:v0.4.4

image account should use starcoin

---

block-relayer/src/block_relayer.rs
block-relayer/src/metrics.rs

remove block_broadcast, add block_broadcast_time.

[block_relayer]block_broadcast_time.

---

block-relayer/src/block_relayer.rs
miner/src/create_block_template/mod.rs
sync/src/block_connector/write_block_chain.rs
types/src/system_events.rs

[block relayer]broadcast_compact_block.

---

Cargo.lock
cmd/resource-exporter/Cargo.toml
network-p2p/types/src/lib.rs
sync/src/txn_sync/mod.rs

NetworkServiceRef 延迟获取，避免初始化的时候，NetworkService 尚未完成，导致 TxnSyncService 初始化失败。
2021-04-01T04:01:19.361436+08:00 ERROR - Create service starcoin_sync::txn_sync::TxnSyncService error: Can not find shared data by type: starcoin_network::service_ref::NetworkServiceRef

[network] logger detail for problem on the network.

---

Cargo.lock
config/src/network_config.rs
config/src/rpc_config.rs
network-rpc/api/src/lib.rs
network-rpc/src/rpc.rs
network/api/src/lib.rs
network/api/src/messages.rs
network/src/service.rs
network/src/service_ref.rs
network/tests/network_service_test.rs
node/src/lib.rs
node/src/network_service_factory.rs
node/src/node.rs
node/src/peer_message_handler.rs
sync/src/announcement/mod.rs
sync/src/lib.rs
sync/src/verified_rpc_client.rs
test-helper/src/network.rs
txpool/src/tx_pool_service_impl.rs

1. optimize txn broadcast;
2. upgrade protocol;

Broadcast txn hash

---

network/src/service.rs
sync/src/announcement/mod.rs
sync/src/verified_rpc_client.rs
vm/transaction-builder/src/lib.rs

解決AnnouncementService和NetworkService循環依賴

fix test_get_txns_with_hash_from_pool.

---

Cargo.lock
Cargo.toml
cmd/airdrop/Cargo.toml
cmd/airdrop/README.md
cmd/airdrop/src/main.rs
cmd/starcoin/src/account/export_cmd.rs

also fix the account export cmd.

airdrop cmd

---

cmd/starcoin/src/account/accept_token_cmd.rs
cmd/starcoin/src/account/change_password_cmd.rs
cmd/starcoin/src/account/create_cmd.rs
cmd/starcoin/src/account/default_cmd.rs
cmd/starcoin/src/account/derive_account_address_cmd.rs
cmd/starcoin/src/account/execute_script_cmd.rs
cmd/starcoin/src/account/execute_script_function_cmd.rs
cmd/starcoin/src/account/export_cmd.rs
cmd/starcoin/src/account/import_cmd.rs
cmd/starcoin/src/account/import_multisig_cmd.rs
cmd/starcoin/src/account/import_readonly_cmd.rs
cmd/starcoin/src/account/list_cmd.rs
cmd/starcoin/src/account/lock_cmd.rs
cmd/starcoin/src/account/receipt_identifier_cmd.rs
cmd/starcoin/src/account/show_cmd.rs
cmd/starcoin/src/account/sign_cmd.rs
cmd/starcoin/src/account/sign_multisig_txn_cmd.rs
cmd/starcoin/src/account/submit_multisig_txn_cmd.rs
cmd/starcoin/src/account/transfer_cmd.rs
cmd/starcoin/src/account/unlock_cmd.rs
cmd/starcoin/src/account/verify_sign_cmd.rs
cmd/starcoin/src/view.rs
testsuite/features/cmd.feature

1. 增加了一些 cmd 的文档。
2. 命令中间输出信息都通过 eprintln 输出，避免破坏命令的 json 输出。
3. 交易签名以及提交时打印出了 json 格式，方便 review。

[cli] Add more account command's document, and print transaction json when sign and commit txn.

---

commons/scmd/src/context.rs

[cli] Enhancement cli, execute quit action when CTRL-C and CTRL-D, fix console version command.

---

cmd/starcoin/src/dev/compile_cmd.rs
developer.starcoin.org/content/setup/runcustomnetwork.zh.md

Enhancement compile cmd error handle

---

developer.starcoin.org/static/rpc/postman/starcoin.postman_collection.json

1. delete un-public folder: account
2. add folder: poll

add demo of poll in developer-rpc-postman

---

README.md

So it turns out some links in README.md are broken. This PR fixes them. 
Feel free to close it.

[readme] fix broken links in README.md

---

Cargo.lock
vm/move-cli/Cargo.toml
vm/move-cli/src/functional_test/mod.rs
vm/move-cli/src/lib.rs
vm/move-cli/src/main.rs
vm/move-cli/src/test.rs

move-cli: support functional-test

---

cmd/starcoin/src/account/show_cmd.rs
cmd/starcoin/src/state/get_cmd.rs
cmd/starcoin/src/state/list_resource_cmd.rs
rpc/api/src/state/mod.rs
rpc/api/src/types.rs
rpc/client/src/lib.rs
rpc/server/src/module/state_rpc.rs
testsuite/features/cmd.feature

重新实现了 state get 命令，resource 返回 decode 后的结果，code 返回 ModuleABI
list resource 暂时没动，接口如何设计还没想好

[cli] Refactor state get command with new ABI api.

---

vm/transaction-builder-generator/src/generate.rs

change java sdk package name from com.starcoin to org.starcoin

change java sdk package name

---

executor/src/account.rs
vm/functional-tests/src/config/global.rs
vm/functional-tests/src/tests/global_config_tests.rs
vm/functional-tests/tests/testsuite/incubator/SortedLinkedList.move

Support assign address to account.
```
//! account: alice 0x07fa08a855753f0ff7292fdcbe871216 10000 0x1::STC::STC 100
```

functional-test: support specify address when declare accounts

---

cmd/starcoin/src/account/show_cmd.rs
cmd/starcoin/src/contract.rs
cmd/starcoin/src/view.rs
rpc/api/src/types.rs
vm/types/src/token/token_code.rs

account show 用 state.list_resource 接口替代 state.get_account_state_set 接口

[cli] `account show` command use `state.list_resource` command for list balance.

---

abi/decoder/src/lib.rs
abi/resolver/src/lib.rs
abi/types/src/lib.rs
rpc/api/src/types.rs
rpc/server/src/module/contract_rpc.rs
vm/types/src/access_path.rs
vm/vm-status-translator/src/lib.rs

自动解析 TransactionOutputView 里的 value, 将 resource 展示为 json object,  方便检查交易影响的 resource。

[rpc] Auto decode the TransactionOutputView's value

---

cmd/starcoin/src/dev/package_cmd.rs
cmd/starcoin/src/dev/tests.rs
cmd/starcoin/src/dev/upgrade_module_plan_cmd.rs
vm/transaction-builder/src/lib.rs

[cli] Add dao_token option to module-plan command
[cli] Add package_hash as result for dev package command.

Fix module-plain command

---

cmd/genesis-nft-miner/src/main.rs

[genesis-nft-miner] fix genesis nft miner sequence number bug.

---

rpc/server/src/module/chain_rpc.rs

ignore decode error.
closing #2817

fix error when decoding failed txn

---

vm/move-cli/src/dependencies.rs
vm/move-cli/src/lib.rs
vm/move-cli/src/main.rs
vm/move-cli/src/remote_state.rs

修复 Reilost 遇到的问题。
但是 `0x1::Debug::debug_print` 这样的直接调用，暂时无法检测出。需要改写成 `use 0x1::Debug` 。

fix move check on remote state

---

Cargo.lock
commons/metrics/Cargo.toml

Reverts starcoinorg/starcoin#2898

Revert "Bump hyper from 0.13.10 to 0.14.12"

---

network/api/src/lib.rs
network/api/src/peer_provider.rs
network/api/src/peer_score.rs

[network] Denny integer_arithmetic in network api mod

---

cmd/starcoin/src/lib.rs
cmd/starcoin/src/node/network/ban_peer_cmd.rs
cmd/starcoin/src/node/network/mod.rs
network-p2p/src/service.rs
network/api/src/lib.rs
network/api/src/messages.rs
network/api/src/peer_provider.rs
network/src/service.rs
network/src/service_ref.rs
rpc/api/src/network_manager.rs
rpc/client/src/lib.rs
rpc/generated_rpc_schema/network_manager.json
rpc/server/src/module/network_manager_rpc.rs
test-helper/src/dummy_network_service.rs

* Add cmd to ban peer
Next step:
* Trigger it after peer reputation below the min value

network: swarm ban peer

---

docker/Dockerfile
docker/Dockerfilefromlocal

fix docker image name

---

block-relayer/src/block_relayer.rs
storage/src/block/mod.rs
storage/src/lib.rs
storage/src/storage.rs
storage/src/tests/test_block.rs
sync/src/block_connector/block_connector_service.rs
sync/src/tasks/block_sync_task.rs

save failed block with config crate_version

save failed block with config crate_version

---

cmd/starcoin/src/dev/gen_block_cmd.rs
miner/src/create_block_template/mod.rs
miner/src/create_block_template/test_create_block_template.rs
miner/src/lib.rs
miner/tests/miner_test.rs
node/src/node.rs
node/src/rpc_service_factory.rs
rpc/server/src/module/debug_rpc.rs
test-helper/src/txpool.rs
testsuite/features/cmd.feature

fix #3036 
dev 模式下，默认禁止打空块，会导致链上时间更新不及时。新增逻辑，如果超过一小时未出块，则强制生成一个新块。
同时重命名 CreateBlockTemplateService 为 BlockBuilderService

Fix dev block produce bug

---

commons/accumulator/src/accumulator_test.rs
commons/accumulator/src/inmemory/accumulator_test.rs
commons/accumulator/src/inmemory/mod.rs
commons/accumulator/src/lib.rs
commons/accumulator/src/node_index.rs
commons/accumulator/src/proof/mod.rs
storage/src/tests/test_accumulator.rs

[accumulator] Support proof for in memory accumulator

---

config/src/storage_config.rs
node/src/node.rs
storage/src/cache_storage/mod.rs
storage/src/chain_info/mod.rs
storage/src/db_storage/mod.rs
storage/src/storage.rs

set db upgrade writeoptions use nonsync

db upgrade nonsync

---

vm/move-package-manager/Cargo.toml

mpm: unit test need testing feature on starcoin vm

mpm: fix unit test

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml
kube/manifest/starcoin-proxima.yaml

kube: update version

---

Cargo.lock
storage/Cargo.toml

Mac M1 compile error revert rocksdb version to 0.17

---

Cargo.lock
testsuite/Cargo.toml
testsuite/tests/steps/cmd.rs

Fix testsuite

---

cmd/starcoin/src/cli_state.rs
rpc/client/src/lib.rs

Use submit hex tx in account transfer

---

vm/move-package-manager/src/releasement.rs

Print package hash when release package.  Maybe need to write a release info file to keep some release info for human-friendly. 
-
-
-

[mpm] Change the default version to v4, and output package hash after release

---

Cargo.lock
cmd/db-exporter/src/main.rs
commons/forkable-jellyfish-merkle/src/iterator/mod.rs
network-rpc/api/src/remote_chain_state.rs
rpc/client/Cargo.toml
rpc/client/src/remote_state_reader.rs
state/api/src/chain_state.rs
state/service/Cargo.toml
state/service/src/service.rs
state/state-tree/Cargo.toml
state/state-tree/src/lib.rs
state/state-tree/src/state_tree.rs
state/state-tree/src/state_tree_test.rs
state/statedb/src/lib.rs
state/statedb/src/tests.rs

add statedb dump iterator 
-
-
-

add statetdb dump_iter

---

.github/ISSUE_TEMPLATE/01_BUG_REPORT.md
.github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
.github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
.github/ISSUE_TEMPLATE/config.yml
README.md
node/src/node.rs
rpc/client/src/chain_watcher.rs
rpc/client/src/lib.rs

Change Log level and Improve README and issue template

---

.github/workflows/benchmark_pr.yml
.github/workflows/build_test.yml
.github/workflows/codecov.yml
bors.toml

[ci] Config bors

---

Cargo.lock
state/state-tree/Cargo.toml
state/state-tree/src/mock/mod.rs
state/state-tree/src/state_tree_test.rs

add statetree multi commit only one flush, missing node test
-
-
-

add statetree flush test

---

cmd/starcoin/src/dev/package_cmd.rs
vm/compiler/src/lib.rs
vm/move-package-manager/src/compatibility_check_cmd.rs
vm/stdlib/src/main.rs

1. [mpm] Output more info for mpm compatibility_check command
2. [cli] dev package command does not downgrade the bytecode

[mpm] Output more info for mpm compatibility check command

---

CONTRIBUTING.md
README.md

[doc] Add rust-coding-guidelines to CONTRIBUTING doc.

---

.github/workflows/release_asset.yml

[release] Fix release yaml file

---

README.md
code_layout.md

Add Code Layout Overview doc

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml
kube/manifest/starcoin-proxima.yaml

update version 1.11.7-rc

---

config/src/network_config.rs

The misprint of help information of the `starcoin` client.
Fix help information.

fix typo of help information of `starcoin` cli

---

README.md

update build from source link

---

Cargo.lock
commons/forkable-jellyfish-merkle/Cargo.toml
commons/forkable-jellyfish-merkle/src/jellyfish_merkle_test.rs

add example explain Blob crypto_hash
-
-
-

add crypto_hash Blob example use sha3

---

cmd/db-exporter/src/main.rs
state/statedb/src/lib.rs

fix import snapshot bug on barnard
-
-
-

fix import  snapshot bug

---

vm/starcoin-transactional-test-harness/Cargo.toml
vm/transaction-builder-generator/src/rust.rs
vm/transaction-builder-generator/tests/generation.rs

update generator crates version and edition

---

.cargo/config
vm/stdlib/.cargo/config.toml

fix windows stack overflow by using link-arg

---

Cargo.lock
abi/resolver/src/lib.rs
chain/api/Cargo.toml
chain/api/src/chain.rs
chain/src/chain.rs
chain/tests/test_epoch_switch.rs
cmd/db-exporter/src/main.rs
cmd/starcoin/src/state/list_cmd.rs
executor/benchmark/src/lib.rs
executor/src/block_executor.rs
executor/src/executor.rs
executor/tests/executor_test.rs
executor/tests/module_upgrade_test.rs
genesis/src/lib.rs
network-rpc/api/src/remote_chain_state.rs
rpc/client/src/remote_state_reader.rs
rpc/server/src/module/contract_rpc.rs
state/api/src/chain_state.rs
state/api/src/lib.rs
state/service/src/service.rs
state/statedb/src/lib.rs
test-helper/src/dao.rs
test-helper/src/executor.rs
vm/dev/src/playground.rs
vm/resource-viewer/src/lib.rs
vm/starcoin-transactional-test-harness/src/in_memory_state_cache.rs
vm/starcoin-transactional-test-harness/src/remote_state.rs
vm/types/src/state_view.rs
vm/vm-runtime/src/data_cache.rs
vm/vm-runtime/src/starcoin_vm.rs

Issue Number: https://github.com/starcoinorg/starcoin/issues/3490
-
-
-

StateView using static dispatch replace dynamic dispatch

---

scripts/monitor_autoscaler_recreate.py

fix type error for action of ci scaler monitor

---

Cargo.lock
cmd/db-exporter/Cargo.toml
cmd/db-exporter/src/main.rs
commons/accumulator/src/tree.rs

- [x ] Code style update (formatting, renaming)
- [x ] Build related changes
-
-
-

bump indicatif 0.15->0.16.2 and fix typo

---

commons/accumulator/src/accumulator_test.rs
commons/accumulator/src/lib.rs
commons/accumulator/src/tree.rs

improve accumulator append
-
-
-

improve accumulator append

---

scripts/sync_block.py

use more instead of less in sync block

---

miner/src/generate_block_event_pacemaker.rs
miner/src/lib.rs
miner/tests/miner_test.rs
node/src/lib.rs
rpc/server/src/module/debug_rpc.rs
types/src/system_events.rs

废弃了 GenerateSleepBlockEvent，在 GenerateBlockEvent 增加字段来表达是否跳过空块检查，简化 GenerateBlockEvent 的处理逻辑。

[miner] Refactor GenerateBlockEvent

---

config/src/lib.rs
config/src/rpc_config.rs
config/src/tests.rs
testsuite/tests/steps/node.rs

Change the default devnet data dir
Issue Number: #3569
- Change the -n dev default random data path to $HOME/.starcoin/dev/
- Check the node starts  multiple times

Change the default devnet data dir

---

.gitattributes

delete  Move syntax highlighting To display rust
No
No

delete  Move syntax highlighting To display rust

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
devtools/x/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

[dep][move] update starcoin/move dep

---

config/src/lib.rs
config/src/tests.rs

fix missing option

---

.github/workflows/sync_blocks.yml
scripts/backup_snapshot.py
scripts/check_sync_snapshot_result.py
scripts/sync_block.py
scripts/sync_snapshot.py

make the check logic work right, and let sync blocks, sync snapshot stand alone

fix sync snapshot check logic && make sync blocks, snapshot stand alone 

---

README.md
scripts/install_starcoin_mpm.sh

provide install script for the latest starcoin and mpm from the lastest  GitHub release page.

provide install script for the latest starcoin and mpm

---

cmd/starcoin/src/main.rs
node/src/lib.rs

[config] fixdevnet config load muilti time

---

scripts/wrk/README.md
scripts/wrk/post-list-resource.lua

Issue Number: https://github.com/starcoinorg/starcoin/pull/3526#issuecomment-1193439348
-
-
-

[scripts] add wrk benchmarking scripts

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml

https://github.com/starcoinorg/starcoin/issues/3624

update main barnard to v1.11.13

---

rpc/server/src/module/state_rpc.rs
types/src/filter.rs
vm/types/src/lib.rs

Provide type_tag_match and contract event filter support struct tag match
Do some refactor based on @YusongWang work #3615
Issue Number: #3614 
-
-
-

[type] provide type_tag_match and contract event filter support struct tag match

---

Cargo.lock
chain/src/verifier/mod.rs
commons/forkable-jellyfish-merkle/Cargo.toml
commons/forkable-jellyfish-merkle/src/lib.rs

add import snapshot debug log
-
-
-

add import snapshot debug log

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
devtools/x/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/natives/src/token.rs
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

update move to a new revision which fix the test failure issue
Current implementation of starcoin/move has some problems when processing account address, and some test cases failed when running `cargo test`. Update starcoin to a new revision which have fixed the address problems
- [] Build related changes
This is just a temporary solution, need to update to an official starcoin/move git revision once https://github.com/starcoinorg/move/pull/10 has been merged
Issue Number: https://github.com/starcoinorg/move/issues/8
-
-
-

update move to a new revision

---

contrib-contracts/modules/EthStateVerifier.move
contrib-contracts/modules/MerkleDistributor.move

`assert(` is deprecated in
https://github.com/diem/diem/pull/9348
-
-
-

[test] replace assert with assert! in move

---

vm/types/src/account_address.rs

[test] fix address in `address_hash` test

---

scripts/auto_rerun_test.ps1
scripts/auto_rerun_test.sh
vm/starcoin-transactional-test-harness/tests/cases/arg_variable.exp
vm/types/src/unit_tests/access_path_test.rs

add multiple space match to grep some failure output 
- [*] Build related changes
Issue Number: fix #3652
-
-
-

[ci] fix ci not fail when some testcase failed

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
devtools/x/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/natives/src/token.rs
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/starcoin-transactional-test-harness/tests/cases/arg_variable.exp
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

update move to a new revision to solve short address problem
Current implementation support short and long representation of account address when parsing
and use long representation when displaying all the time 
-
-
-

update move to a new revision to solve short address problem

---

.github/workflows/build_test.yml

add manual dispatch to workflow build and test

---

vm/starcoin-transactional-test-harness/src/context.rs
vm/starcoin-transactional-test-harness/src/fork_chain.rs
vm/starcoin-transactional-test-harness/src/fork_state.rs
vm/starcoin-transactional-test-harness/src/lib.rs
vm/starcoin-transactional-test-harness/src/remote_state.rs
vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd.exp
vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd.move

- 解决[这里](https://github.com/starcoinorg/starcoin/pull/3600#issuecomment-1221262407)提到的通过 parent hash 获取 block   出错的问题。
- 根据 @baichuan3 提供的测试 case，和对 Block::Checkpoint 的理解做了简单修改。完整的测试 case 在[这里](https://gist.github.com/0xpause/79be034b2234cb0abe1196a725865a27)，这几个 case 均通过测试。
- mpm 里面的 parent hash 还存在一个问题：mpm block 指令支持任意指定 block number，因此 parent 是按照实际调用 block 指令的顺序确定的，与实际的 block number 不一定对应。

mpm fix parent hash

---

.github/workflows/auto_bump_homebrew.yml

use COMMITTER_TOKEN instead of GITHUB_TOKEN

---

Cargo.lock
vm/move-package-manager/Cargo.toml

fix mpm package test using table_extension.
-
-
-

[dev branch]fix mpm package table test

---

vm/move-package-manager/src/lib.rs
vm/starcoin-transactional-test-harness/src/lib.rs

- Print usage of mpm integration-test tasks, like run, faucet, call-api, etc.
- Print all tasks usages: `mpm integration-test --task-help`
- Print specific task usage: `mpm integration-test --task-help --task-name init`

print usage of mpm integration-test tasks.

---

.github/workflows/build_test.yml

[ci] test with nextest

---

vm/starcoin-transactional-test-harness/src/lib.rs

This is a fixed bug in #3691 but re-introduced in #3716.

fix mistake introduced in #3716

---

.github/workflows/build_test.yml

Issue Number: #3721 
-
-
-
`   FLAKY 3/4 [  47.579s]                                   starcoin-cmd dev::tests::test_upgrade_module` in log is to be addressed in #3733

[ci] tweak ci test, add doc test

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/db-exporter/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
devtools/x/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

[move]Update move for pickup changes

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml

Update version v1.12.4

---

scripts/check_sync_snapshot_result.py

For snapshot check, 
Temp draft, and should be tested after new release online.

adapt new starcoin_db_exporter add state_node_prev check 

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/db-exporter/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
devtools/x/Cargo.toml
state/api/src/chain_state.rs
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/types/src/genesis_config.rs
vm/types/src/state_view.rs
vm/vm-runtime/Cargo.toml
vm/vm-runtime/src/starcoin_vm.rs

[move]Upgrade move and for fix bug

---

cmd/db-exporter/src/main.rs

use starcoin_db_export export_snapshot -i ~/.starcoin/main -n main -o ~/snaposhot
print 'increment export snapshot manifest.cvs error'
-
-
-

fix export snapshot

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml

Update version v1.12.5

---

consensus/cryptonight-rs/ext/oaes_lib.c

Issue Number: try fix https://github.com/starcoinorg/starcoin/pull/3710#issuecomment-1259177757
-
-
-

fix compilation issue of cyptonight on windows

---

.github/workflows/codecov.yml
scripts/nextest.sh

reduce coverage testing time from 45min to 12min
-
-
-
relate to: https://github.com/starcoinorg/starcoin/issues/3699

[code-cov] `cargo llvm-cov nextest` to generate coverage data

---

.github/workflows/release_asset.yml

Release for ubuntu-22.04

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/db-exporter/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

update starcoin-move to latest

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml

update version v1.12.6

---

vm/stdlib/README.md

- fix the half-width formatting of dash (`-`)
- add migration instructions for starcoin-framework
- format the contents

Update `vm/stdlib/README.md` to make it pretty

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
cmd/db-exporter/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
executor/Cargo.toml
test-helper/Cargo.toml
vm/compiler/Cargo.toml
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml

Diff https://github.com/starcoinorg/move/compare/1844005dcfc828ff009b7af2cc7a1eeda87995f9...8a38b689ea033de63c444f4519e2254a9cee7f40
-
-
-

[move] Pickup fixs and update move

---

config/src/genesis_config.rs
kube/manifest/aws/cluster-autoscaler-policy.json
kube/manifest/aws/deploy_auto_scaler.sh
kube/manifest/aws/load_balancer.sh
kube/manifest/runner/runner.yaml
kube/manifest/service-barnard.yaml
kube/manifest/service-halley.yaml
kube/manifest/service-main.yaml
kube/manifest/service-proxima.yaml
kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-halley.yaml
kube/manifest/starcoin-main.yaml
kube/manifest/starcoin-proxima.yaml
scripts/prometheus_conf/prometheus.yml

- autoscaler -> v1.23.0
- aws lb -> v2.4.5
- main and barnard seed pvc to 300g
- update cluster-autoscaler-policy
- update replicas for testnets: 
- barnard 3 replicas
- proxima 1 replica
- halley 1 replica

Update k8s manifest

---

Cargo.lock
abi/decoder/Cargo.toml
abi/resolver/Cargo.toml
abi/resolver/src/lib.rs
cmd/db-exporter/Cargo.toml
cmd/starcoin/Cargo.toml
commons/proptest-helpers/Cargo.toml
executor/Cargo.toml
test-helper/Cargo.toml
vm/compiler/Cargo.toml
vm/compiler/src/lib.rs
vm/move-coverage/Cargo.toml
vm/move-explain/Cargo.toml
vm/move-package-manager/Cargo.toml
vm/move-package-manager/src/compatibility_check_cmd.rs
vm/move-prover/Cargo.toml
vm/natives/Cargo.toml
vm/resource-viewer/Cargo.toml
vm/starcoin-transactional-test-harness/Cargo.toml
vm/stdlib/Cargo.toml
vm/stdlib/src/main.rs
vm/transaction-builder-generator/Cargo.toml
vm/types/Cargo.toml
vm/vm-runtime/Cargo.toml
vm/vm-runtime/tests/test_native_functions.rs

fix publish_module_bundle
-
-
-

fix publish_module_bundle

---

chain/api/src/errors.rs
network/src/service.rs
node/src/node.rs
storage/src/block/mod.rs
storage/src/chain_info/mod.rs
storage/src/lib.rs
storage/src/storage.rs
storage/src/upgrade.rs
sync/src/block_connector/write_block_chain.rs
sync/src/tasks/block_sync_task.rs
types/src/startup_info.rs
vm/move-package-manager/src/release.rs
vm/starcoin-transactional-test-harness/tests/cases/call_api_cmd_halley.exp

Barnard hard fork test

---

Cargo.lock
network-p2p/Cargo.toml
network-p2p/src/service.rs
network-p2p/src/service_test.rs
network/tests/network_service_test.rs

network-p2p: Service use tokio spawn as executor

---

executor/tests/executor_test.rs
vm/types/src/access_path.rs

https://github.com/starcoinorg/starcoin/issues/3844
add test code
-
-
-

add transfer transaction result INSUFFICIENT_BALANCE_FOR_TRANSACTION_FEE test

---

.github/workflows/release_asset.yml

Fix release failed

---

Cargo.lock
Cargo.toml
commons/proptest-helpers/Cargo.toml
vm/starcoin-gas/src/gas_meter.rs

https://github.com/starcoinorg/move/pull/55
-
-
-

cherry pick recent security

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml
kube/manifest/starcoin-proxima.yaml
vm/vm-runtime/src/natives.rs

update main, barnard, proxima kube config images
-
-
-

update main,banard,proxima kube config image

---

vm/move-package-manager/src/lib.rs

fix mpm intergration_test
-
-
-

fix mpm intergration_test

---

Cargo.lock
Cargo.toml
commons/proptest-helpers/Cargo.toml

https://github.com/starcoinorg/move/pull/56
-
-
-

fix get_successor and verifier

---

Cargo.lock
Cargo.toml

fix https://github.com/starcoinorg/starcoin/pull/3881 starcoin-framework repo
-
-
-

update starcoin-framework repo

---

rust-toolchain.toml

Issue Number:   #3892 
- Build the project sucessfully
-
-

upgrade rust version from 1.66.0 to 1.66.1

---

vm/vm-runtime/src/starcoin_vm.rs

remove starcoin_vm.rs unused code
-
-
-

remove starcoin_vm.rs unused code

---

Cargo.lock
Cargo.toml

Update rocksdb for fixing librocksdb_sys build failed when llvm >= 15.0.6

---

vm/gas-algebra-ext/Cargo.toml
vm/gas-algebra-ext/src/move_stdlib.rs
vm/types/Cargo.toml

fix gas-algebra-ext move_stdlib test
-
-
-

fix gas-algebra-ext move_stdlib test

---

Cargo.lock
Cargo.toml

related https://github.com/starcoinorg/move/pull/59
-
-
-

cherry-pick: improved value depth checks in the VM

---

cmd/db-exporter/src/cmd_batch_execution.rs
cmd/db-exporter/src/main.rs
cmd/db-exporter/src/verify_module.rs
cmd/resource-exporter/src/main.rs
vm/types/src/lib.rs

rustfmt crates and remove unecessary functions

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml

update net main barnard kube config

---

Cargo.lock
Cargo.toml

Limit type tag size

---

kube/manifest/starcoin-barnard.yaml
kube/manifest/starcoin-main.yaml
kube/manifest/starcoin-proxima.yaml

update proxima,barnard,main net image

---

vm/types/src/on_chain_config/gas_schedule.rs
vm/types/src/on_chain_config/mod.rs
vm/vm-runtime/src/starcoin_vm.rs

[typo] fix typo in stdlib v12 relate with GasSchedule.move

---

chain/open-block/src/lib.rs
chain/src/chain.rs
executor/benchmark/src/lib.rs
executor/src/block_executor.rs
genesis/src/lib.rs
rpc/api/src/types.rs
storage/src/lib.rs
storage/src/table_info/mod.rs
storage/src/tests/test_storage.rs
vm/starcoin-transactional-test-harness/src/fork_chain.rs
vm/starcoin-transactional-test-harness/src/lib.rs
vm/types/src/transaction/mod.rs
vm/vm-runtime/src/move_vm_ext/session.rs
vm/vm-runtime/src/starcoin_vm.rs

Feat tableinfo v2

---

Cargo.lock
chain/api/src/chain.rs
chain/api/src/message.rs
chain/api/src/service.rs
chain/service/Cargo.toml
chain/service/src/chain_service.rs
chain/src/chain.rs
config/src/genesis_config.rs
consensus/src/dag/blockdag.rs
network-rpc/api/src/lib.rs
network-rpc/src/rpc.rs
network/src/network_p2p_handle.rs
network/src/service.rs
network/types/src/peer_info.rs
node/src/node.rs
storage/src/lib.rs
sync/src/block_connector/write_block_chain.rs
sync/src/sync.rs
sync/src/tasks/block_sync_task.rs
sync/src/tasks/mod.rs
sync/src/tasks/sync_dag_accumulator_task.rs
sync/src/tasks/sync_dag_block_task.rs
sync/src/tasks/sync_dag_full_task.rs
sync/src/verified_rpc_client.rs
test-helper/src/network.rs
types/src/block.rs
types/src/startup_info.rs
types/src/sync_status.rs

debug sync successfully

---

sync/src/block_connector/test_illegal_block.rs
sync/src/block_connector/write_block_chain.rs

check if dag or not to try to connect the block

---

sync/src/block_connector/test_illegal_block.rs
sync/src/block_connector/write_block_chain.rs

check if dag or not to try to connect the main

---

chain/chain-notify/src/lib.rs
consensus/src/dag/blockdag.rs
flexidag/src/flexidag_service.rs
network/api/src/peer_provider.rs
storage/src/lib.rs
storage/src/tests/test_dag.rs

fix flexidag service compile error

---

Cargo.lock
Cargo.toml
cmd/db-exporter/src/main.rs
vm/mvhashmap/Cargo.toml
vm/parallel-executor/Cargo.toml
vm/proptest-helpers/Cargo.toml

fix types oom

---

README.md

use Starcoin Linktree

---

Cargo.lock
Cargo.toml

Reference to the Move repository that has been fixed

---

node/src/node.rs

disable dragon hard fork

---

.github/workflows/docker_build.yml
chain/open-block/src/lib.rs
kube/manifest/starcoin-barnard.yaml
network/src/service.rs
storage/src/upgrade.rs

Rollback for Force deploy on  barnard network

---

chain/api/src/message.rs
chain/api/src/service.rs
chain/service/src/chain_service.rs
sync/src/sync.rs
sync/src/tasks/accumulator_sync_task.rs
sync/src/tasks/inner_sync_task.rs
sync/src/tasks/mod.rs

add get fork number in chain service

---

chain/api/src/message.rs
chain/api/src/service.rs
chain/service/src/chain_service.rs
sync/src/sync.rs
sync/src/tasks/accumulator_sync_task.rs
sync/src/tasks/inner_sync_task.rs
sync/src/tasks/mod.rs
sync/src/tasks/test_tools.rs
sync/src/tasks/tests.rs
sync/src/tasks/tests_dag.rs

Dag mining net dev

---

Cargo.lock
cmd/miner_client/Cargo.toml
miner/src/lib.rs
stratum/Cargo.toml
stratum/src/diff_manager.rs
stratum/src/lib.rs
stratum/src/rpc.rs
stratum/src/stratum.rs

Support stcbox and starcoin_miner client to connect to starcoin node mining by stratum protocol. 
Implement a stratum server within starcoin node and support dispatch mining sub-job with
a suitable difficulty caculated by the hash rate

Miner pool support

---

chain/src/chain.rs
chain/tests/test_txn_info_and_proof.rs
config/src/genesis_config.rs
executor/tests/error_code_test.rs
sync/src/block_connector/test_write_dag_block_chain.rs
sync/tests/common_test_sync_libs.rs
sync/tests/full_sync_test.rs
sync/tests/test_rpc_client.rs
types/src/block/mod.rs

[Dag Sync]Fix sync test case

---

.github/workflows/docker_build.yml
kube/manifest/starcoin-halley.yaml

Build docker for dag-master and deploy to halley with 3 replica

---

chain/api/src/message.rs
chain/api/src/service.rs
chain/service/src/chain_service.rs
flexidag/src/blockdag.rs
flexidag/src/consensusdb/consenses_state.rs
flexidag/src/ghostdag/protocol.rs
flexidag/tests/tests.rs
kube/manifest/starcoin-proxima.yaml
sync/src/sync.rs

[FlexiDag] set HeaderWithBlockLevel block_level 1 and fix some typos
-
-
-

[FlexiDag] set HeaderWithBlockLevel block_level 1 and fix some typos

---

chain/service/src/chain_service.rs
flexidag/tests/tests.rs
network-p2p/src/protocol/generic_proto/tests.rs
network/tests/network_service_test.rs
storage/src/block/mod.rs
storage/src/lib.rs
storage/src/storage.rs
storage/src/tests/test_block.rs
sync/src/block_connector/test_write_dag_block_chain.rs
sync/src/block_connector/write_block_chain.rs
sync/src/tasks/block_sync_task.rs
sync/src/tasks/test_tools.rs
sync/src/tasks/tests.rs
sync/src/tasks/tests_dag.rs
sync/tests/common_test_sync_libs.rs
sync/tests/test_rpc_client.rs

Remove dag sync blocks

---

chain/src/verifier/mod.rs
network/api/src/messages.rs
storage/src/tests/test_storage.rs
types/src/block/mod.rs
types/src/compact_block.rs

Prune unsupported feature

---

chain/api/src/message.rs
chain/api/src/service.rs
chain/service/src/chain_service.rs
flexidag/src/types/ghostdata.rs
rpc/api/generated_rpc_schema/chain.json
rpc/api/src/chain/mod.rs
rpc/server/src/module/chain_rpc.rs
vm/starcoin-transactional-test-harness/src/fork_chain.rs

Ghostdagdata rpc

---

sync/src/block_connector/write_block_chain.rs

Return future block error to trigger the sync to get other dag blocks

---

cmd/faucet/src/faucet.rs
cmd/tx-factory/src/main.rs
network-rpc/api/src/lib.rs
network-rpc/api/src/remote_chain_state.rs
network-rpc/src/rpc.rs
rpc/client/src/remote_state_reader.rs
rpc/server/src/module/chain_rpc.rs
rpc/server/src/module/contract_rpc.rs
state/api/src/chain_state.rs
state/service/src/service.rs
state/statedb/src/lib.rs
txpool/src/pool_client.rs

fix starcoin-network-rpc errors

---

Cargo.lock
chain/open-block/src/lib.rs
executor/src/block_executor.rs
genesis/src/lib.rs
rpc/api/src/types.rs
vm/types/src/access_path.rs
vm/types/src/contract_event.rs
vm/types/src/event.rs
vm/types/src/state_store/mod.rs
vm/types/src/transaction/mod.rs
vm/types/src/transaction/package.rs
vm/types/src/write_set.rs
vm/vm-runtime-types/Cargo.toml
vm/vm-runtime-types/src/abstract_write_op.rs
vm/vm-runtime-types/src/change_set.rs
vm/vm-runtime-types/src/lib.rs
vm/vm-runtime-types/src/module_write_set.rs
vm/vm-runtime-types/src/output.rs
vm/vm-runtime-types/src/resolver.rs
vm/vm-runtime/src/data_cache.rs
vm/vm-runtime/src/lib.rs
vm/vm-runtime/src/move_vm_ext/mod.rs
vm/vm-runtime/src/move_vm_ext/resolver.rs
vm/vm-runtime/src/move_vm_ext/session.rs
vm/vm-runtime/src/move_vm_ext/warm_vm_cache.rs
vm/vm-runtime/src/move_vm_ext/write_op_converter.rs
vm/vm-runtime/src/parallel_executor/mod.rs
vm/vm-runtime/src/starcoin_vm.rs

Refactor move vm ext

---

vm/move-package-manager/src/main.rs
vm/move-package-manager/src/release.rs

[compiler-v2 framework] fixed mpm opt parse error

---

etc/starcoin_types.yml
vm/types/src/account_config/constants/account.rs
vm/types/src/account_config/resources/account.rs
vm/types/src/account_config/resources/balance.rs
vm/types/src/account_config/resources/coin_store.rs
vm/types/src/account_config/resources/mod.rs

fixed the account show command in console

---

vm/types/src/account_config/constants/account.rs
vm/vm-runtime/src/move_vm_ext/session.rs
vm/vm-runtime/src/starcoin_vm.rs

[compiler-v2 framework] Fixed execution parameter check

---

abi/decoder/src/lib.rs
vm/vm-runtime/src/move_vm_ext/session.rs
vm/vm-runtime/src/verifier/transaction_arg_validation.rs

[compiler-v2 framework] Fixed the error of function params signer reference

---

types/src/account.rs
vm/framework/starcoin-framework/doc/account.md
vm/framework/starcoin-framework/sources/account.move
vm/framework/starcoin-framework/sources/stc/block_reward.move
vm/framework/starcoin-framework/sources/stc/consensus_config.move
vm/framework/starcoin-framework/sources/stc/dao.move
vm/starcoin-transactional-test-harness/src/lib.rs
vm/types/src/account_config/constants/account.rs
vm/types/src/account_config/resources/account.rs
vm/types/src/account_config/resources/mod.rs
vm/types/src/on_chain_config/vm_config.rs
vm/types/src/on_chain_resource/block_metadata.rs
vm/types/src/on_chain_resource/mod.rs
vm/types/src/state_view.rs
vm/vm-runtime/src/starcoin_vm.rs
vm/vm-runtime/src/verifier/transaction_arg_validation.rs

compiler v2 framework fixed move package manager harness

---

Cargo.lock
state/statedb/src/tests.rs
types/src/block/tests.rs
vm/types/src/access_path.rs
vm/types/src/account_config/resources/mod.rs
vm/types/src/account_config/resources/object.rs
vm/types/src/state_store/state_key/prefix.rs
vm/types/src/state_store/state_key/tests.rs
vm/vm-runtime-types/Cargo.toml
vm/vm-runtime-types/src/resource_group_adapter.rs
vm/vm-runtime/src/move_vm_ext/write_op_converter.rs
vm/vm-runtime/tests/test_native_functions.rs

[compiler-v2] fix starcoin-statedb and vm-runtime-types test mod errors

---

state/state-tree/src/state_tree.rs
state/statedb/src/lib.rs
vm/vm-runtime/src/data_cache.rs
vm/vm-runtime/src/parallel_executor/storage_wrapper.rs
vm/vm-runtime/src/starcoin_vm.rs

[compiler-v2] update statedb cache

---

Cargo.lock
Cargo.toml
vm/framework/starcoin-framework/doc/dao.md
vm/types/src/access_path.rs
vm/types/src/state_store/state_key/mod.rs
vm/types/src/state_store/state_key/tests.rs

[compiler-v2] fix AccessPath unit test

---

vm/framework/move-stdlib/doc/features.md
vm/framework/move-stdlib/sources/configs/features.move
vm/framework/starcoin-framework/doc/account.md
vm/framework/starcoin-framework/doc/coin.md
vm/framework/starcoin-framework/doc/consensus_strategy.md
vm/framework/starcoin-framework/doc/genesis.md
vm/framework/starcoin-framework/doc/starcoin_account.md
vm/framework/starcoin-framework/doc/stc_block.md
vm/framework/starcoin-framework/doc/stc_genesis.md
vm/framework/starcoin-framework/doc/stc_transaction_package_validation.md
vm/framework/starcoin-framework/doc/stc_transaction_publish_option.md
vm/framework/starcoin-framework/doc/stc_transaction_validation.md
vm/framework/starcoin-framework/doc/stc_util.md
vm/framework/starcoin-framework/doc/vesting.md
vm/framework/starcoin-framework/integration-tests/account/txn_prologue_and_epilogue.exp
vm/framework/starcoin-framework/integration-tests/account/txn_prologue_and_epilogue.move
vm/framework/starcoin-framework/sources/coin.move
vm/framework/starcoin-framework/sources/genesis.move
vm/framework/starcoin-framework/sources/starcoin_account.move
vm/framework/starcoin-framework/sources/starcoin_account.spec.move
vm/framework/starcoin-framework/sources/stc/consensus_strategy.move
vm/framework/starcoin-framework/sources/stc/stc_block.move
vm/framework/starcoin-framework/sources/stc/stc_genesis.move
vm/framework/starcoin-framework/sources/stc/stc_transaction_package_validation.move
vm/framework/starcoin-framework/sources/stc/stc_transaction_publish_option.move
vm/framework/starcoin-framework/sources/stc/stc_util.move
vm/framework/starcoin-framework/sources/vesting.move

[compiler-v2] fixed compare 0x1::starcoin_coin::STC 

---

Cargo.lock
Cargo.toml

[compiler-v2] revert access path

---

executor/tests/executor_test.rs
test-helper/src/executor.rs
test-helper/src/txn.rs
types/src/account.rs
vm/framework/starcoin-framework/doc/coin.md
vm/framework/starcoin-framework/doc/stc_transaction_validation.md
vm/framework/starcoin-framework/doc/stc_util.md
vm/framework/starcoin-framework/doc/transfer_scripts.md
vm/framework/starcoin-framework/sources/stc/stc_transaction_validation.move
vm/framework/starcoin-framework/sources/stc/transfer_scripts.move
vm/types/src/account_config/events/block_reward.rs
vm/types/src/transaction/mod.rs
vm/vm-runtime/src/errors.rs

Fix executor test

---

rpc/api/generated_rpc_schema/account.json
rpc/api/generated_rpc_schema/chain.json
rpc/api/generated_rpc_schema/contract_api.json
rpc/api/generated_rpc_schema/node.json
rpc/api/generated_rpc_schema/state.json
rpc/api/generated_rpc_schema/sync_manager.json
rpc/api/generated_rpc_schema/txpool.json

[compiler-v2]fix starcoin rpc api

---

account/service/src/account_events.rs
cmd/starcoin/src/view.rs
rpc/api/src/types.rs
test-helper/src/executor.rs
types/src/filter.rs
vm/types/src/contract_event.rs
vm/vm-runtime/src/natives.rs
vm/vm-runtime/src/starcoin_vm.rs

[compiler-v2] fixed event v2

---

config/src/genesis_config.rs
config/src/tests.rs
vm/gas-schedule/src/gas_schedule/instr.rs
vm/types/src/on_chain_config/gas_schedule.rs

[compiler-v2] fix starcoin config unit test

---

Cargo.lock
chain/tests/block_test_utils.rs
executor/benchmark/src/lib.rs
executor/tests/executor_test.rs
scripts/nextest.sh
storage/src/transaction/test.rs
types/Cargo.toml
types/src/block/legacy.rs
types/src/block/tests.rs
types/src/lib.rs
types/src/proptest_types.rs

Fix types tests

---

network-rpc/api/src/lib.rs
network-rpc/api/src/remote_chain_state.rs
network-rpc/src/rpc.rs
network-rpc/src/tests.rs

[compiler-v2] fix starcoin-network-rpc unit test

---

Cargo.lock
Cargo.toml
executor/tests/script_function_test.rs
scripts/nextest.sh
vm/stdlib/Cargo.toml
vm/stdlib/src/lib.rs
vm/stdlib/src/main.rs
vm/stdlib/tests/generated_files.rs

[compiler-v2] remove legacy framework

---

vm/move-package-manager/src/package.rs
vm/move-package-manager/src/release.rs

[compiler-v2]fix mpm command

---

Cargo.lock
Cargo.toml
vm/stdlib/src/lib.rs

[compiler-v2] fixed stdlib build warning reported by move-prover

---

config/src/genesis_config.rs

[compiler-v2] proxima update dag_effective_height

---

chain/force-upgrade/src/lib.rs
chain/open-block/src/lib.rs
chain/tests/test_force_upgrade.rs
vm/vm-runtime/src/force_upgrade_management.rs
vm/vm-runtime/src/starcoin_vm.rs

Donot charge force upgrade txn

---

.github/workflows/build_test.yml
chain/tests/test_txn_info_and_proof.rs
etc/starcoin_types.yml
rpc/api/src/types.rs
vm/types/src/transaction/mod.rs
vm/vm-runtime/src/adapter_common.rs
vm/vm-runtime/src/starcoin_vm.rs

Transaction add UserTransactionExt
-
-
-

[multi-vm] Transaction add UserTransactionExt

---

executor/src/executor.rs
vm/e2e-tests/src/executor.rs
vm/transaction-benchmarks/src/transactions.rs
vm/vm-runtime/src/lib.rs
vm/vm-runtime/src/starcoin_vm.rs

select default vm executor to fix tests

---

Cargo.lock
genesis/Cargo.toml
genesis/tests/generated_files.rs
rpc/api/Cargo.toml
rpc/api/src/tests.rs
test-helper/src/lib.rs
test-helper/src/utils.rs
vm/stdlib/Cargo.toml
vm/stdlib/tests/generated_files.rs

fix unclean git status errors

---

Cargo.lock
Cargo.toml
chain/open-block/src/lib.rs
chain/src/chain.rs
commons/forkable-jellyfish-merkle/Cargo.toml
commons/forkable-jellyfish-merkle/benches/bench_merkle_tree.rs
commons/forkable-jellyfish-merkle/src/jellyfish_merkle_test.rs
genesis/src/lib.rs
rpc/api/src/multi_types.rs
types/src/lib.rs

unifiy crate HashValue

---

Cargo.lock
Cargo.toml

rm legacy starcoin-crypto

---

Cargo.lock
commons/infallible/Cargo.toml
commons/infallible/src/lib.rs
commons/infallible/src/math.rs
commons/infallible/src/nonzero.rs
commons/infallible/src/rwlock.rs
commons/infallible/src/time.rs
commons/metrics/Cargo.toml
commons/metrics/src/lib.rs
commons/metrics/src/op_counters.rs
commons/metrics/src/process_collector.rs
commons/timeout-join-handler/Cargo.toml
commons/timeout-join-handler/src/lib.rs
vm2/executor/src/block_executor.rs
vm2/executor/src/lib.rs
vm2/genesis/src/lib.rs

Update shared deps

---

Cargo.lock
Cargo.toml

upgrade vm2 shared crates

---

Cargo.lock
Cargo.toml
chain/Cargo.toml
chain/api/src/lib.rs
chain/mock/src/mock_chain.rs
chain/service/src/chain_service.rs
chain/src/chain.rs
executor/src/block_executor.rs
miner/src/create_block_template/mod.rs
miner/src/create_block_template/test_create_block_template.rs
rpc/api/src/types.rs
rpc/server/src/module/pubsub/tests.rs
sync/src/block_connector/test_illegal_block.rs
sync/src/block_connector/test_write_block_chain.rs
sync/src/block_connector/write_block_chain.rs
sync/src/tasks/inner_sync_task.rs
sync/src/tasks/tests.rs
test-helper/src/chain.rs
test-helper/tests/types_check.rs
types/src/lib.rs
types/src/transaction.rs
vm/types/src/transaction/mod.rs
vm2/chain/src/lib.rs
vm2/executor/src/block_executor.rs
vm2/genesis/src/lib.rs

Fix listing txn info

---

types/src/view/mod.rs

reexport types::view and add ContractCall

---

Cargo.lock
Cargo.toml
account/provider/Cargo.toml
account/provider/src/lib.rs
account/provider/src/provider2.rs
account/provider/src/rpc_provider2.rs
vm2/executor/Cargo.toml
vm2/executor/src/block_executor.rs
vm2/executor/src/executor.rs

Add vm2 account provider

---

Cargo.lock
Cargo.toml
vm2/rpc/server/Cargo.toml
vm2/rpc/server/src/lib.rs
vm2/rpc/server/src/state_rpc.rs

add rpc2 server state_rpc

---

Cargo.lock
Cargo.toml
vm2/rpc/server/Cargo.toml
vm2/rpc/server/src/contract_rpc.rs
vm2/rpc/server/src/lib.rs
vm2/rpc/server/src/state_rpc.rs

vm rpc2 server contract rpc

---

Cargo.lock
chain/api/src/lib.rs
chain/open-block/src/lib.rs
chain/src/chain.rs
node/src/node.rs
types/src/multi_transaction.rs
vm2/chain/Cargo.toml
vm2/chain/src/lib.rs
vm2/executor/src/executor.rs
vm2/service/account/src/service.rs

Remove some unwraps

---

Cargo.lock
cmd/starcoin/Cargo.toml
cmd/starcoin/src/cli_state.rs
cmd/starcoin/src/cli_state_vm2.rs
cmd/starcoin/src/main.rs
cmd/starcoin/src/view_vm2.rs
rpc/client/src/vm2.rs
vm/move-package-manager/src/deployment.rs

Adds previously blocked processing details in CliStateVM2
-
-
-

[multi move vm] add account provider vm2 for clistate vm2

---

types/src/view/resource_view.rs

[starcoin-vm2] add ResourceView missing decode function

---

cmd/starcoin/src/subcommand_vm2/account/show_cmd.rs

[multi-move] fixed fmt

---

Cargo.lock
Cargo.toml
cmd/starcoin/Cargo.toml
cmd/starcoin/src/main.rs
cmd/starcoin/src/subcommand_vm2/account/show_cmd.rs
cmd/starcoin/src/subcommand_vm2/dev/get_coin_cmd.rs
cmd/starcoin/src/subcommand_vm2/dev/mod.rs
cmd/starcoin/src/subcommand_vm2/mod.rs
config/src/lib.rs
rpc/client/src/vm2.rs

1. Because the CmdContext execution process is inconsistent with expectations, the GlobalOpt VM2 switch is removed and the vm2 subcommand is used instead.
2. Solved some TODO
-
-
-

[multi move-vm] cmds fix todo and add dev2 commands

---

rpc/server/src/module/chain_rpc.rs
state/statedb/src/lib.rs
txpool/src/lib.rs
txpool/src/tx_pool_service_impl.rs

Fix some state root errors

---

Cargo.lock
txpool/Cargo.toml
txpool/api/Cargo.toml
txpool/api/src/lib.rs
txpool/mock-service/Cargo.toml
txpool/mock-service/src/lib.rs
txpool/src/pool_client.rs
txpool/src/tx_pool_service_impl.rs

 txpool api add next_sequence_number2

---

chain/mock/src/mock_chain.rs
chain/service/src/chain_service.rs
chain/tests/block_test_utils.rs
chain/tests/test_txn_info_and_proof.rs
genesis/src/lib.rs
miner/src/create_block_template/test_create_block_template.rs
miner/tests/miner_test.rs
scripts/nextest.sh
state/service/src/service.rs
sync/src/block_connector/test_write_block_chain.rs
sync/src/tasks/tests.rs
test-helper/src/chain.rs
test-helper/src/network.rs
test-helper/src/txpool.rs
vm/types/src/transaction/mod.rs
vm/types/src/transaction/stc_transaction.rs
vm2/service/state/src/service.rs

Fix more tests

---

docker/Dockerfile
docker/Dockerfilefromlocal
scripts/release.sh

[multi move] fixed ci deploy

---

.github/workflows/build_test.yml
Cargo.lock
chain/open-block/src/lib.rs
chain/open-block/src/vm2.rs
chain/src/chain.rs
cmd/starcoin/Cargo.toml
cmd/starcoin/src/lib.rs
cmd/starcoin/src/state/get_cmd.rs
cmd/starcoin/src/state/get_proof_cmd.rs
cmd/starcoin/src/state/get_root_cmd.rs
cmd/starcoin/src/state/list_cmd.rs
cmd/starcoin/src/subcommand_vm2/account/rotate_auth_key_cmd.rs
cmd/starcoin/src/subcommand_vm2/account/verify_sign_cmd.rs
storage/src/storage.rs
storage/src/upgrade.rs
testsuite/features/cmd.feature
testsuite/tests/steps/cmd.rs

Enable integration tests

---

cmd/resource-code-exporter/tests/import_test.rs

[multi-move] ignore slow test

---

rpc/api/generated_rpc_schema/chain.json
rpc/api/src/chain/mod.rs
rpc/api/src/types.rs
rpc/client/src/lib.rs
rpc/client/src/remote_state_reader.rs
rpc/client/src/remote_state_reader2.rs
rpc/server/src/module/chain_rpc.rs
test-helper/src/starcoin_dao.rs
vm/starcoin-transactional-test-harness/src/fork_chain.rs

Fix state reader root

---

cmd/starcoin/src/chain/get_events_cmd.rs
cmd/starcoin/src/cli_state.rs
cmd/starcoin/src/view.rs
rpc/client/src/lib.rs

remove a duplicated function

---

Cargo.lock
Cargo.toml
kube/manifest/starcoin-main.yaml
network-p2p/src/protocol.rs
network-p2p/src/service.rs

network-p2p: Init peerset with notif_protocols
